In [ ]:
! pip install altair_saver vl-convert-python

Collecting altair_saver
  Downloading altair_saver-0.5.0-py3-none-any.whl.metadata (5.2 kB)
Collecting vl-convert-python
  Downloading vl_convert_python-1.9.0.post1-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: altair in /usr/local/lib/python3.12/dist-packages (from altair_saver) (5.5.0)
Collecting altair-data-server>=0.4.0 (from altair_saver)
  Downloading altair_data_server-0.4.1-py3-none-any.whl.metadata (4.0 kB)
Collecting altair-viewer (from altair_saver)
  Downloading altair_viewer-0.4.0-py3-none-any.whl.metadata (4.1 kB)
Collecting selenium (from altair_saver)
  Downloading selenium-4.45.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: portpicker in /usr/local/lib/python3.12/dist-packages (from altair-data-server>=0.4.0->altair_saver) (1.5.2)
Requirement already satisfied: tornado in /usr/local/lib/python3.12/dist-packages (from altair-data-server>=0.4.0->altair_saver) (6.5.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair->altair_saver) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair->altair_saver) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair->altair_saver) (2.22.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from altair->altair_saver) (26.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from altair->altair_saver) (4.15.0)
Requirement already satisfied: certifi>=2026.2.25 in /usr/local/lib/python3.12/dist-packages (from selenium->altair_saver) (2026.5.20)
Collecting trio<1.0,>=0.31.0 (from selenium->altair_saver)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium->altair_saver)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium->altair_saver)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium->altair_saver) (1.9.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair->altair_saver) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair->altair_saver) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair->altair_saver) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair->altair_saver) (2026.5.1)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium->altair_saver)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->altair_saver) (3.18)
Collecting outcome (from trio<1.0,>=0.31.0->selenium->altair_saver)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->altair_saver) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium->altair_saver)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium->altair_saver) (1.7.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair->altair_saver) (3.0.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from portpicker->altair-data-server>=0.4.0->altair_saver) (5.9.5)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium->altair_saver) (0.16.0)
Downloading altair_saver-0.5.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.3/89.3 kB 2.9 MB/s eta 0:00:00
Downloading vl_convert_python-1.9.0.post1-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 47.6 MB/s eta 0:00:00
Downloading altair_data_server-0.4.1-py3-none-any.whl (12 kB)
Downloading altair_viewer-0.4.0-py3-none-any.whl (844 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 844.5/844.5 kB 43.2 MB/s eta 0:00:00
Downloading selenium-4.45.0-py3-none-any.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 85.8 MB/s eta 0:00:00
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.3/510.3 kB 31.7 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.1/131.1 kB 5.3 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, wsproto, vl-convert-python, urllib3, outcome, trio, trio-websocket, selenium, altair-data-server, altair-viewer, altair_saver
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
Successfully installed altair-data-server-0.4.1 altair-viewer-0.4.0 altair_saver-0.5.0 outcome-1.3.0.post0 selenium-4.45.0 sortedcontainers-2.4.0 trio-0.33.0 trio-websocket-0.12.2 urllib3-2.7.0 vl-convert-python-1.9.0.post1 wsproto-1.3.2

In [ ]:
import pandas as pd
import altair as alt

In [ ]:
df = pd.read_csv("/content/Base de datos infante.csv", sep=';')

In [ ]:
import os
os.listdir('/content/')

['.config',
 'grafico_rango_tasa_2012_2022.html',
 'grafico_rango_tasa_1993_2022.html',
 'Base de datos infante.csv',
 'sample_data']

In [ ]:
df.head()

,ano,region,nacidos_vivos,tasa_natalidad_1000,porcentajes_madres_extranjeras
0,2024,tarapaca,0.0,"10,5",0
1,2024,arica_parinacota,0.0,"9,1",0
2,2024,antofagasta,0.0,"8,8",0
3,2024,maule,0.0,8,0
4,2024,atacama,0.0,"8,9",0

In [ ]:
df.columns

Index(['ano', 'region', 'nacidos_vivos', 'tasa_natalidad_1000',
       'porcentajes_madres_extranjeras'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 512 entries, 0 to 511
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ano                             512 non-null    int64
 1   region                          512 non-null    object
 2   nacidos_vivos                   512 non-null    float64
 3   tasa_natalidad_1000             512 non-null    object
 4   porcentajes_madres_extranjeras  512 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 20.1+ KB

In [ ]:
df.describe()

               ano  nacidos_vivos
count   512.000000     512.000000
mean   2008.500000      15.901115
std       9.242123      48.288035
min    1993.000000       0.000000
25%    2000.750000       2.493250
50%    2008.500000       8.775500
75%    2016.250000      13.718000
max    2024.000000     982.000000

In [ ]:
df["ano"].unique()

array([2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014,
       2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003,
       2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993])

In [ ]:
df["region"].unique()

array(['tarapaca', 'arica_parinacota', 'antofagasta', 'maule', 'atacama',
       'la_araucania', 'ohiggins', 'los_lagos', 'biobio', 'aysen',
       'nuble', 'coquimbo', 'los_rios', 'metropolitana', 'valparaiso',
       'magallanes'], dtype=object)

In [ ]:
df[df["ano"].isin([2023, 2024])]

,ano,region,nacidos_vivos,tasa_natalidad_1000,porcentajes_madres_extranjeras
0,2024,tarapaca,0.0,"10,5",0
1,2024,arica_parinacota,0.0,"9,1",0
2,2024,antofagasta,0.0,"8,8",0
3,2024,maule,0.0,8,0
4,2024,atacama,0.0,"8,9",0
5,2024,la_araucania,0.0,"8,4",0
6,2024,ohiggins,0.0,"8,1",0
7,2024,los_lagos,0.0,"8,2",0
8,2024,biobio,0.0,"7,7",0
9,2024,aysen,0.0,"7,4",0
10,2024,nuble,0.0,"7,9",0
11,2024,coquimbo,0.0,"7,6",0
12,2024,los_rios,0.0,"7,7",0
13,2024,metropolitana,0.0,"7,2",0
14,2024,valparaiso,0.0,"7,3",0
15,2024,magallanes,0.0,"6,8",0
16,2023,tarapaca,0.0,"11,6",0
17,2023,arica_parinacota,0.0,"10,6",0
18,2023,antofagasta,0.0,"9,8",0
19,2023,maule,0.0,"9,3",0
20,2023,atacama,0.0,"9,8",0
21,2023,la_araucania,0.0,"9,4",0
22,2023,ohiggins,0.0,"8,9",0
23,2023,los_lagos,0.0,"9,1",0
24,2023,biobio,0.0,"8,8",0
25,2023,aysen,0.0,9,0
26,2023,nuble,0.0,"9,1",0
27,2023,coquimbo,0.0,"8,6",0
28,2023,los_rios,0.0,"8,8",0
29,2023,metropolitana,0.0,"8,2",0
30,2023,valparaiso,0.0,"8,4",0
31,2023,magallanes,0.0,"7,9",0

In [ ]:
df_limpia = df[df["ano"] <= 2022]

In [ ]:
import pandas as pd
df = pd.read_csv("/content/Base de datos infante.csv", sep=';')

df_limpia = df[df["ano"] <= 2022].copy()

# Convert 'tasa_natalidad_1000' to numeric, handling commas as decimal separators
if df_limpia['tasa_natalidad_1000'].dtype == 'object':
    df_limpia.loc[:, "tasa_natalidad_1000"] = df_limpia["tasa_natalidad_1000"].str.replace(',', '.', regex=False).astype(float)

# Convert 'porcentajes_madres_extranjeras' to numeric, handling commas and '0000000000000000'
if df_limpia['porcentajes_madres_extranjeras'].dtype == 'object':
    df_limpia.loc[:, "porcentajes_madres_extranjeras"] = (
        df_limpia["porcentajes_madres_extranjeras"]
        .astype(str)
        .str.replace(',', '.', regex=False)
        .replace('0000000000000000', '0')
        .astype(float)
    )

display(df_limpia.head())

,ano,region,nacidos_vivos,tasa_natalidad_1000,porcentajes_madres_extranjeras
32,2022,tarapaca,5.023,12.7,47.9
33,2022,arica_parinacota,2.916,11.3,38.1
34,2022,antofagasta,7.484,10.6,40.6
35,2022,maule,11.837,10.3,10.3
36,2022,atacama,3.265,10.3,20.1

In [ ]:
df_limpia.head()

,ano,region,nacidos_vivos,tasa_natalidad_1000,porcentajes_madres_extranjeras
32,2022,tarapaca,5.023,12.7,47.9
33,2022,arica_parinacota,2.916,11.3,38.1
34,2022,antofagasta,7.484,10.6,40.6
35,2022,maule,11.837,10.3,10.3
36,2022,atacama,3.265,10.3,20.1

In [ ]:
nacimientos_por_ano = df_limpia.groupby("ano")["nacidos_vivos"].sum().reset_index()
nacimientos_por_ano

     ano  nacidos_vivos
0   1993        270.400
1   1994        273.766
2   1995        265.922
3   1996        265.093
4   1997        249.959
5   1998        247.105
6   1999        250.674
7   2000        248.893
8   2001        246.116
9   2002        238.981
10  2003        234.486
11  2004        243.450
12  2005        242.949
13  2006        231.383
14  2007        240.569
15  2008        246.581
16  2009        252.240
17  2010        244.639
18  2011        241.432
19  2012        243.635
20  2013        242.005
21  2014        250.997
22  2015        244.670
23  2016        231.749
24  2017        219.186
25  2018        221.731
26  2019        210.188
27  2020        194.978
28  2021       1158.291
29  2022        189.303

In [ ]:
nacimientos_por_ano.sort_values("nacidos_vivos", ascending=False)

     ano  nacidos_vivos
28  2021       1158.291
1   1994        273.766
0   1993        270.400
2   1995        265.922
3   1996        265.093
16  2009        252.240
21  2014        250.997
6   1999        250.674
4   1997        249.959
7   2000        248.893
5   1998        247.105
15  2008        246.581
8   2001        246.116
22  2015        244.670
17  2010        244.639
19  2012        243.635
11  2004        243.450
12  2005        242.949
20  2013        242.005
18  2011        241.432
14  2007        240.569
9   2002        238.981
10  2003        234.486
23  2016        231.749
13  2006        231.383
25  2018        221.731
24  2017        219.186
26  2019        210.188
27  2020        194.978
29  2022        189.303

In [ ]:
nacimientos_por_ano.sort_values("nacidos_vivos", ascending=True)

     ano  nacidos_vivos
29  2022        189.303
27  2020        194.978
26  2019        210.188
24  2017        219.186
25  2018        221.731
13  2006        231.383
23  2016        231.749
10  2003        234.486
9   2002        238.981
14  2007        240.569
18  2011        241.432
20  2013        242.005
12  2005        242.949
11  2004        243.450
19  2012        243.635
17  2010        244.639
22  2015        244.670
8   2001        246.116
15  2008        246.581
5   1998        247.105
7   2000        248.893
4   1997        249.959
6   1999        250.674
21  2014        250.997
16  2009        252.240
3   1996        265.093
2   1995        265.922
0   1993        270.400
1   1994        273.766
28  2021       1158.291

In [ ]:
if df_limpia['tasa_natalidad_1000'].dtype == 'object':
    df_limpia.loc[:, "tasa_natalidad_1000"] = df_limpia["tasa_natalidad_1000"].astype(str).str.replace(',', '.', regex=False).astype(float)
tasa_por_ano = df_limpia.groupby("ano")["tasa_natalidad_1000"].mean().reset_index()
tasa_por_ano

     ano tasa_natalidad_1000
0   1993               16.45
1   1994            15.95625
2   1995               15.25
3   1996                15.1
4   1997               14.55
5   1998            14.21875
6   1999             13.7375
7   2000              13.425
8   2001              13.175
9   2002              12.725
10  2003                12.4
11  2004            14.56875
12  2005            14.53125
13  2006               13.85
14  2007            14.19375
15  2008              14.575
16  2009            14.75625
17  2010            14.54375
18  2011             14.2125
19  2012             14.3125
20  2013            14.01875
21  2014             14.3125
22  2015            13.54375
23  2016            12.76875
24  2017             11.9125
25  2018            11.61875
26  2019             10.9125
27  2020             10.1875
28  2021              9.2125
29  2022                9.95

In [ ]:
if df_limpia['porcentajes_madres_extranjeras'].dtype == 'object':
    df_limpia.loc[:, "porcentajes_madres_extranjeras"] = (
        df_limpia["porcentajes_madres_extranjeras"]
        .astype(str)
        .str.replace(',', '.', regex=False)
        .replace('0000000000000000', '0')
        .astype(float)
    )
madres_extranjeras_por_ano = df_limpia.groupby("ano")["porcentajes_madres_extranjeras"].sum().reset_index()
madres_extranjeras_por_ano

     ano porcentajes_madres_extranjeras
0   1993                            0.0
1   1994                            0.0
2   1995                            0.0
3   1996                            0.0
4   1997                            0.0
5   1998                            0.0
6   1999                            0.0
7   2000                            0.0
8   2001                            0.0
9   2002                            0.0
10  2003                            0.0
11  2004                            0.0
12  2005                            0.0
13  2006                            0.0
14  2007                            0.0
15  2008                            0.0
16  2009                            0.0
17  2010                            0.0
18  2011                            0.0
19  2012                            0.0
20  2013                            0.0
21  2014                            0.0
22  2015                           72.3
23  2016                          118.6
24  2017                          125.4
25  2018                          180.7
26  2019                          213.6
27  2020                          225.9
28  2021                          244.6
29  2022                          269.4

In [ ]:
madres_extranjeras_por_ano.sort_values("porcentajes_madres_extranjeras", ascending=False)

     ano porcentajes_madres_extranjeras
29  2022                          269.4
28  2021                          244.6
27  2020                          225.9
26  2019                          213.6
25  2018                          180.7
24  2017                          125.4
23  2016                          118.6
22  2015                           72.3
1   1994                            0.0
21  2014                            0.0
20  2013                            0.0
19  2012                            0.0
18  2011                            0.0
17  2010                            0.0
16  2009                            0.0
0   1993                            0.0
14  2007                            0.0
13  2006                            0.0
12  2005                            0.0
11  2004                            0.0
10  2003                            0.0
9   2002                            0.0
8   2001                            0.0
7   2000                            0.0
6   1999                            0.0
5   1998                            0.0
4   1997                            0.0
3   1996                            0.0
2   1995                            0.0
15  2008                            0.0

In [ ]:
comparacion_anual = pd.merge(nacimientos_por_ano, tasa_por_ano, on="ano")
comparacion_anual

     ano  nacidos_vivos tasa_natalidad_1000
0   1993        270.400               16.45
1   1994        273.766            15.95625
2   1995        265.922               15.25
3   1996        265.093                15.1
4   1997        249.959               14.55
5   1998        247.105            14.21875
6   1999        250.674             13.7375
7   2000        248.893              13.425
8   2001        246.116              13.175
9   2002        238.981              12.725
10  2003        234.486                12.4
11  2004        243.450            14.56875
12  2005        242.949            14.53125
13  2006        231.383               13.85
14  2007        240.569            14.19375
15  2008        246.581              14.575
16  2009        252.240            14.75625
17  2010        244.639            14.54375
18  2011        241.432             14.2125
19  2012        243.635             14.3125
20  2013        242.005            14.01875
21  2014        250.997             14.3125
22  2015        244.670            13.54375
23  2016        231.749            12.76875
24  2017        219.186             11.9125
25  2018        221.731            11.61875
26  2019        210.188             10.9125
27  2020        194.978             10.1875
28  2021       1158.291              9.2125
29  2022        189.303                9.95

In [ ]:
comparacion_anual = df_limpia.groupby("ano").agg({"nacidos_vivos": "sum", "tasa_natalidad_1000": "mean", "porcentajes_madres_extranjeras" : "mean"}).reset_index()
comparacion_anual

     ano  nacidos_vivos tasa_natalidad_1000 porcentajes_madres_extranjeras
0   1993        270.400               16.45                            0.0
1   1994        273.766            15.95625                            0.0
2   1995        265.922               15.25                            0.0
3   1996        265.093                15.1                            0.0
4   1997        249.959               14.55                            0.0
5   1998        247.105            14.21875                            0.0
6   1999        250.674             13.7375                            0.0
7   2000        248.893              13.425                            0.0
8   2001        246.116              13.175                            0.0
9   2002        238.981              12.725                            0.0
10  2003        234.486                12.4                            0.0
11  2004        243.450            14.56875                            0.0
12  2005        242.949            14.53125                            0.0
13  2006        231.383               13.85                            0.0
14  2007        240.569            14.19375                            0.0
15  2008        246.581              14.575                            0.0
16  2009        252.240            14.75625                            0.0
17  2010        244.639            14.54375                            0.0
18  2011        241.432             14.2125                            0.0
19  2012        243.635             14.3125                            0.0
20  2013        242.005            14.01875                            0.0
21  2014        250.997             14.3125                            0.0
22  2015        244.670            13.54375                        4.51875
23  2016        231.749            12.76875                         7.4125
24  2017        219.186             11.9125                         7.8375
25  2018        221.731            11.61875                       11.29375
26  2019        210.188             10.9125                          13.35
27  2020        194.978             10.1875                       14.11875
28  2021       1158.291              9.2125                        15.2875
29  2022        189.303                9.95                        16.8375

In [ ]:
comparacion_anual = df_limpia.groupby("ano").agg({"nacidos_vivos": "sum", "tasa_natalidad_1000": "mean", "porcentajes_madres_extranjeras" : "mean"}).reset_index()
comparacion_anual = comparacion_anual.sort_values("ano", ascending=False)
comparacion_anual

     ano  nacidos_vivos tasa_natalidad_1000 porcentajes_madres_extranjeras
29  2022        189.303                9.95                        16.8375
28  2021       1158.291              9.2125                        15.2875
27  2020        194.978             10.1875                       14.11875
26  2019        210.188             10.9125                          13.35
25  2018        221.731            11.61875                       11.29375
24  2017        219.186             11.9125                         7.8375
23  2016        231.749            12.76875                         7.4125
22  2015        244.670            13.54375                        4.51875
21  2014        250.997             14.3125                            0.0
20  2013        242.005            14.01875                            0.0
19  2012        243.635             14.3125                            0.0
18  2011        241.432             14.2125                            0.0
17  2010        244.639            14.54375                            0.0
16  2009        252.240            14.75625                            0.0
15  2008        246.581              14.575                            0.0
14  2007        240.569            14.19375                            0.0
13  2006        231.383               13.85                            0.0
12  2005        242.949            14.53125                            0.0
11  2004        243.450            14.56875                            0.0
10  2003        234.486                12.4                            0.0
9   2002        238.981              12.725                            0.0
8   2001        246.116              13.175                            0.0
7   2000        248.893              13.425                            0.0
6   1999        250.674             13.7375                            0.0
5   1998        247.105            14.21875                            0.0
4   1997        249.959               14.55                            0.0
3   1996        265.093                15.1                            0.0
2   1995        265.922               15.25                            0.0
1   1994        273.766            15.95625                            0.0
0   1993        270.400               16.45                            0.0

In [ ]:
df_limpia[["ano", "region", "nacidos_vivos", "tasa_natalidad_1000", "porcentajes_madres_extranjeras"]].sort_values(by=["ano", "tasa_natalidad_1000"], ascending=[False, False])

,ano,region,nacidos_vivos,tasa_natalidad_1000,porcentajes_madres_extranjeras
32,2022,tarapaca,5.023,12.7,47.9
33,2022,arica_parinacota,2.916,11.3,38.1
34,2022,antofagasta,7.484,10.6,40.6
35,2022,maule,11.837,10.3,10.3
36,2022,atacama,3.265,10.3,20.1
...,...,...,...,...,...
510,1993,valparaiso,27.101,19.0,0.0
511,1993,magallanes,2.633,17.8,0.0
497,1993,arica_parinacota,0.000,0.0,0.0
506,1993,nuble,0.000,0.0,0.0
508,1993,los_rios,0.000,0.0,0.0

In [ ]:
print(df_limpia['ano'].unique())

[2022 2021 2020 2019 2018 2017 2016 2015 2014 2013 2012 2011 2010 2009
 2008 2007 2006 2005 2004 2003 2002 2001 2000 1999 1998 1997 1996 1995
 1994 1993]

In [ ]:
pd.set_option('display.max_rows', None)

df_limpia[["ano", "region", "nacidos_vivos", "tasa_natalidad_1000", "porcentajes_madres_extranjeras"]].sort_values(by=["ano", "tasa_natalidad_1000"], ascending=[False, False])

,ano,region,nacidos_vivos,tasa_natalidad_1000,porcentajes_madres_extranjeras
32,2022,tarapaca,5.023,12.7,47.9
33,2022,arica_parinacota,2.916,11.3,38.1
34,2022,antofagasta,7.484,10.6,40.6
35,2022,maule,11.837,10.3,10.3
36,2022,atacama,3.265,10.3,20.1
37,2022,la_araucania,10.405,10.2,3.9
38,2022,ohiggins,10.072,10.0,14.4
39,2022,los_lagos,8.955,9.9,7.9
40,2022,biobio,16.115,9.6,5.9
41,2022,aysen,1.023,9.5,6.5
42,2022,nuble,4.838,9.4,5.7
43,2022,coquimbo,8.019,9.4,12.8
44,2022,los_rios,3.780,9.3,3.0
45,2022,metropolitana,76.129,9.2,26.3
46,2022,valparaiso,17.903,9.0,12.6
47,2022,magallanes,1.539,8.5,13.4
48,2021,tarapaca,4.396,11.3,44.9
49,2021,arica_parinacota,2.553,10.0,35.1
53,2021,la_araucania,9.860,9.7,3.4
50,2021,antofagasta,6.748,9.6,37.4
51,2021,maule,10.689,9.4,8.9
54,2021,ohiggins,9.258,9.3,11.4
55,2021,los_lagos,8.370,9.3,7.3
52,2021,atacama,2.920,9.2,16.3
57,2021,aysen,982.000,9.1,5.7
59,2021,coquimbo,7.564,8.9,10.8
61,2021,metropolitana,73.062,8.9,24.5
56,2021,biobio,14.639,8.8,5.6
58,2021,nuble,4.481,8.7,5.0
62,2021,valparaiso,16.822,8.5,11.1
60,2021,los_rios,3.435,8.4,3.6
63,2021,magallanes,1.494,8.3,13.6
64,2020,tarapaca,4.709,12.3,39.2
65,2020,arica_parinacota,2.886,11.5,31.7
66,2020,antofagasta,7.434,10.8,33.5
70,2020,ohiggins,10.245,10.4,11.3
67,2020,maule,11.667,10.3,8.7
68,2020,atacama,3.247,10.3,14.0
69,2020,la_araucania,10.441,10.3,3.8
71,2020,los_lagos,8.958,10.1,7.0
77,2020,metropolitana,81.351,10.0,23.3
73,2020,aysen,1.059,9.9,5.5
75,2020,coquimbo,8.127,9.7,9.5
72,2020,biobio,16.006,9.6,5.1
74,2020,nuble,4.885,9.6,5.2
76,2020,los_rios,3.898,9.6,4.8
78,2020,valparaiso,18.427,9.4,10.8
79,2020,magallanes,1.638,9.2,12.5
80,2019,tarapaca,4.878,13.2,36.9
81,2019,arica_parinacota,2.893,11.7,29.7
82,2019,antofagasta,7.770,11.7,31.1
93,2019,metropolitana,89.770,11.4,22.9
83,2019,maule,12.496,11.2,9.6
85,2019,la_araucania,11.302,11.2,3.7
84,2019,atacama,3.425,11.0,13.3
86,2019,ohiggins,10.756,11.0,11.4
87,2019,los_lagos,9.574,10.8,5.9
91,2019,coquimbo,8.666,10.6,9.6
89,2019,aysen,1.120,10.5,4.5
88,2019,biobio,17.107,10.4,4.4
94,2019,valparaiso,19.619,10.1,11.8
90,2019,nuble,5.065,10.0,4.6
92,2019,los_rios,4.004,9.9,4.2
95,2019,magallanes,1.743,9.9,10.0
96,2018,tarapaca,4.955,14.0,33.7
98,2018,antofagasta,8.049,12.5,28.5
109,2018,metropolitana,95.834,12.5,21.0
97,2018,arica_parinacota,2.958,12.2,22.8
100,2018,atacama,3.730,12.2,10.0
105,2018,aysen,1.258,11.9,4.1
99,2018,maule,13.070,11.8,7.9
101,2018,la_araucania,11.772,11.8,3.2
102,2018,ohiggins,11.248,11.6,9.4
103,2018,los_lagos,9.921,11.3,4.1
107,2018,coquimbo,9.095,11.3,7.6
110,2018,valparaiso,21.002,11.0,9.7
104,2018,biobio,17.652,10.7,2.7
106,2018,nuble,5.324,10.6,4.6
108,2018,los_rios,4.106,10.3,3.3
111,2018,magallanes,1.757,10.2,8.1
112,2017,tarapaca,5.081,14.9,31.7
114,2017,antofagasta,8.396,13.5,24.8
116,2017,atacama,3.929,12.9,7.0
113,2017,arica_parinacota,3.037,12.8,21.1
125,2017,metropolitana,92.727,12.4,14.4
117,2017,la_araucania,12.005,12.1,1.4
115,2017,maule,12.632,11.6,2.0
119,2017,los_lagos,10.046,11.6,1.5
123,2017,coquimbo,9.215,11.6,4.0
121,2017,aysen,1.215,11.5,2.5
118,2017,ohiggins,10.887,11.4,2.9
120,2017,biobio,18.175,11.1,1.5
127,2017,magallanes,1.883,11.0,5.0
126,2017,valparaiso,20.357,10.8,3.0
122,2017,nuble,5.333,10.7,1.5
124,2017,los_rios,4.268,10.7,1.1
128,2016,tarapaca,5.419,15.9,27.5
130,2016,antofagasta,9.214,14.7,22.5
132,2016,atacama,4.230,13.4,6.1
129,2016,arica_parinacota,3.169,13.2,16.9
141,2016,metropolitana,96.616,13.1,9.7
137,2016,aysen,1.408,13.0,1.5
139,2016,coquimbo,10.126,13.0,2.4
135,2016,los_lagos,10.787,12.8,0.9
131,2016,maule,13.225,12.6,0.9
133,2016,la_araucania,12.534,12.6,20.0
134,2016,ohiggins,11.416,12.4,1.5
142,2016,valparaiso,22.165,12.1,2.2
136,2016,biobio,19.582,11.8,0.8
143,2016,magallanes,1.873,11.3,3.9
138,2016,nuble,5.453,11.2,0.8
140,2016,los_rios,4.532,11.2,1.0
144,2015,tarapaca,5.712,17.1,18.6
146,2015,antofagasta,9.885,15.9,16.9
145,2015,arica_parinacota,3.414,14.3,13.2
148,2015,atacama,4.466,14.3,4.9
157,2015,metropolitana,101.087,13.9,6.5
147,2015,maule,14.068,13.5,0.8
149,2015,la_araucania,13.324,13.5,0.6
151,2015,los_lagos,11.158,13.3,1.0
150,2015,ohiggins,12.050,13.2,0.1
153,2015,aysen,1.413,13.1,1.6
155,2015,coquimbo,11.010,13.0,1.8
158,2015,valparaiso,23.598,13.0,1.5
152,2015,biobio,21.023,12.7,0.6
159,2015,magallanes,2.032,12.4,2.9
154,2015,nuble,5.766,11.9,0.6
156,2015,los_rios,4.664,11.6,0.7
160,2014,tarapaca,5.835,17.8,0.0
162,2014,antofagasta,10.191,16.7,0.0
164,2014,atacama,5.014,16.4,0.0
171,2014,coquimbo,11.577,15.3,0.0
161,2014,arica_parinacota,3.546,15.1,0.0
169,2014,aysen,1.535,14.4,0.0
173,2014,metropolitana,103.059,14.3,0.0
163,2014,maule,14.345,13.9,0.0
165,2014,la_araucania,13.313,13.7,0.0
166,2014,ohiggins,12.412,13.7,0.0
167,2014,los_lagos,11.380,13.7,0.0
174,2014,valparaiso,24.125,13.4,0.0
168,2014,biobio,21.599,13.2,0.0
175,2014,magallanes,2.104,12.9,0.0
172,2014,los_rios,5.063,12.6,0.0
170,2014,nuble,5.899,11.9,0.0
176,2013,tarapaca,5.766,18.1,0.0
178,2013,antofagasta,9.841,16.4,0.0
180,2013,atacama,4.849,16.0,0.0
177,2013,arica_parinacota,3.504,15.2,0.0
187,2013,coquimbo,11.343,15.2,0.0
189,2013,metropolitana,99.081,13.9,0.0
183,2013,los_lagos,11.191,13.6,0.0
185,2013,aysen,1.440,13.6,0.0
182,2013,ohiggins,12.113,13.5,0.0
179,2013,maule,13.714,13.4,0.0
181,2013,la_araucania,12.877,13.2,0.0
190,2013,valparaiso,23.127,13.0,0.0
184,2013,biobio,20.714,12.7,0.0
191,2013,magallanes,2.041,12.6,0.0
188,2013,los_rios,4.814,12.2,0.0
186,2013,nuble,5.590,11.7,0.0
192,2012,tarapaca,5.721,18.4,0.0
194,2012,antofagasta,9.817,16.6,0.0
196,2012,atacama,4.855,16.2,0.0
193,2012,arica_parinacota,3.558,15.7,0.0
203,2012,coquimbo,11.217,15.3,0.0
201,2012,aysen,1.540,14.7,0.0
205,2012,metropolitana,99.488,14.1,0.0
199,2012,los_lagos,11.287,13.7,0.0
198,2012,ohiggins,12.119,13.6,0.0
197,2012,la_araucania,13.024,13.4,0.0
206,2012,valparaiso,23.619,13.3,0.0
195,2012,maule,13.429,13.2,0.0
207,2012,magallanes,2.108,13.0,0.0
200,2012,biobio,20.997,12.9,0.0
204,2012,los_rios,5.124,12.9,0.0
202,2012,nuble,5.732,12.0,0.0
209,2011,arica_parinacota,3.640,20.0,0.0
212,2011,atacama,5.116,18.2,0.0
208,2011,tarapaca,5.753,18.1,0.0
210,2011,antofagasta,9.932,17.2,0.0
219,2011,coquimbo,11.148,15.4,0.0
217,2011,aysen,1.545,14.6,0.0
221,2011,metropolitana,100.415,14.5,0.0
215,2011,los_lagos,11.911,14.2,0.0
213,2011,la_araucania,13.295,13.8,0.0
214,2011,ohiggins,12.189,13.8,0.0
216,2011,biobio,21.986,13.7,0.0
220,2011,los_rios,5.176,13.7,0.0
211,2011,maule,13.640,13.5,0.0
223,2011,magallanes,2.118,13.4,0.0
222,2011,valparaiso,23.568,13.3,0.0
218,2011,nuble,0.000,0.0,0.0
225,2010,arica_parinacota,3.646,20.0,0.0
228,2010,atacama,5.069,18.1,0.0
224,2010,tarapaca,5.637,18.0,0.0
226,2010,antofagasta,10.016,17.5,0.0
233,2010,aysen,1.636,15.7,0.0
235,2010,coquimbo,11.225,15.6,0.0
231,2010,los_lagos,12.413,14.9,0.0
237,2010,metropolitana,101.047,14.7,0.0
230,2010,ohiggins,12.723,14.4,0.0
236,2010,los_rios,5.433,14.4,0.0
239,2010,magallanes,2.243,14.2,0.0
227,2010,maule,14.103,14.0,0.0
232,2010,biobio,22.293,13.9,0.0
229,2010,la_araucania,13.367,13.8,0.0
238,2010,valparaiso,23.788,13.5,0.0
234,2010,nuble,0.000,0.0,0.0
241,2009,arica_parinacota,3.559,19.1,0.0
244,2009,atacama,5.194,18.8,0.0
240,2009,tarapaca,5.692,18.7,0.0
242,2009,antofagasta,9.988,17.7,0.0
249,2009,aysen,1.687,16.4,0.0
247,2009,los_lagos,13.072,15.9,0.0
251,2009,coquimbo,10.801,15.3,0.0
253,2009,metropolitana,102.248,15.1,0.0
246,2009,ohiggins,12.731,14.6,0.0
243,2009,maule,14.108,14.2,0.0
245,2009,la_araucania,13.546,14.2,0.0
252,2009,los_rios,5.349,14.2,0.0
248,2009,biobio,28.313,14.1,0.0
255,2009,magallanes,2.217,14.1,0.0
254,2009,valparaiso,23.735,13.7,0.0
250,2009,nuble,0.000,0.0,0.0
257,2008,arica_parinacota,3.364,18.3,0.0
256,2008,tarapaca,5.287,17.8,0.0
260,2008,atacama,4.803,17.5,0.0
258,2008,antofagasta,9.706,17.4,0.0
265,2008,aysen,1.733,17.2,0.0
263,2008,los_lagos,12.772,15.7,0.0
267,2008,coquimbo,10.447,15.1,0.0
269,2008,metropolitana,99.873,14.9,0.0
262,2008,ohiggins,12.592,14.7,0.0
271,2008,magallanes,2.264,14.5,0.0
261,2008,la_araucania,13.494,14.3,0.0
259,2008,maule,14.045,14.2,0.0
268,2008,los_rios,5.306,14.2,0.0
264,2008,biobio,27.779,13.9,0.0
270,2008,valparaiso,23.116,13.5,0.0
266,2008,nuble,0.000,0.0,0.0
276,2007,atacama,4.720,17.3,0.0
272,2007,tarapaca,5.017,17.1,0.0
274,2007,antofagasta,9.419,17.1,0.0
273,2007,arica_parinacota,3.158,16.8,0.0
281,2007,aysen,1.679,16.5,0.0
279,2007,los_lagos,12.335,15.4,0.0
285,2007,metropolitana,97.596,14.7,0.0
283,2007,coquimbo,9.794,14.4,0.0
277,2007,la_araucania,13.418,14.3,0.0
278,2007,ohiggins,12.199,14.3,0.0
280,2007,biobio,27.682,14.0,0.0
287,2007,magallanes,2.173,14.0,0.0
275,2007,maule,13.566,13.9,0.0
284,2007,los_rios,5.154,13.9,0.0
286,2007,valparaiso,22.659,13.4,0.0
282,2007,nuble,0.000,0.0,0.0
292,2006,atacama,4.648,17.1,0.0
288,2006,tarapaca,4.761,16.7,0.0
289,2006,arica_parinacota,3.099,16.6,0.0
290,2006,antofagasta,8.975,16.5,0.0
297,2006,aysen,1.563,16.1,0.0
295,2006,los_lagos,11.758,14.9,0.0
301,2006,metropolitana,93.593,14.3,0.0
293,2006,la_araucania,13.016,14.0,0.0
303,2006,magallanes,2.127,14.0,0.0
299,2006,coquimbo,9.372,13.9,0.0
300,2006,los_rios,5.155,13.8,0.0
296,2006,biobio,27.028,13.7,0.0
294,2006,ohiggins,11.517,13.6,0.0
291,2006,maule,13.099,13.4,0.0
302,2006,valparaiso,21.672,13.0,0.0
298,2006,nuble,0.000,0.0,0.0
304,2005,tarapaca,5.024,18.0,0.0
305,2005,arica_parinacota,3.287,17.2,0.0
308,2005,atacama,4.523,16.7,0.0
313,2005,aysen,1.662,16.7,0.0
306,2005,antofagasta,9.000,16.6,0.0
311,2005,los_lagos,12.642,16.1,0.0
315,2005,coquimbo,9.992,15.0,0.0
317,2005,metropolitana,97.653,14.9,0.0
310,2005,ohiggins,12.408,14.8,0.0
309,2005,la_araucania,13.545,14.6,0.0
319,2005,magallanes,2.271,14.6,0.0
307,2005,maule,14.008,14.5,0.0
316,2005,los_rios,5.355,14.4,0.0
312,2005,biobio,28.170,14.3,0.0
318,2005,valparaiso,23.409,14.1,0.0
314,2005,nuble,0.000,0.0,0.0
320,2004,tarapaca,4.821,17.7,0.0
321,2004,arica_parinacota,3.270,17.1,0.0
322,2004,antofagasta,9.052,17.0,0.0
329,2004,aysen,1.674,17.0,0.0
324,2004,atacama,4.434,16.5,0.0
327,2004,los_lagos,12.442,16.1,0.0
333,2004,metropolitana,97.982,15.2,0.0
325,2004,la_araucania,13.819,15.0,0.0
326,2004,ohiggins,13.382,14.9,0.0
331,2004,coquimbo,9.691,14.8,0.0
332,2004,los_rios,5.410,14.6,0.0
323,2004,maule,13.892,14.5,0.0
328,2004,biobio,28.268,14.5,0.0
334,2004,valparaiso,23.118,14.1,0.0
335,2004,magallanes,2.195,14.1,0.0
330,2004,nuble,0.000,0.0,0.0
336,2003,tarapaca,7.732,18.5,0.0
338,2003,antofagasta,8.663,17.8,0.0
345,2003,aysen,1.578,15.9,0.0
347,2003,coquimbo,9.459,15.7,0.0
343,2003,los_lagos,16.935,15.5,0.0
340,2003,atacama,4.407,15.4,0.0
349,2003,metropolitana,94.728,14.9,0.0
341,2003,la_araucania,13.013,14.4,0.0
342,2003,ohiggins,11.799,14.4,0.0
339,2003,maule,13.453,14.3,0.0
344,2003,biobio,28.040,14.1,0.0
350,2003,valparaiso,22.481,13.9,0.0
351,2003,magallanes,2.198,13.6,0.0
337,2003,arica_parinacota,0.000,0.0,0.0
346,2003,nuble,0.000,0.0,0.0
348,2003,los_rios,0.000,0.0,0.0
352,2002,tarapaca,7.571,18.4,0.0
354,2002,antofagasta,8.842,18.4,0.0
359,2002,los_lagos,17.506,16.2,0.0
361,2002,aysen,1.579,16.2,0.0
363,2002,coquimbo,9.608,16.2,0.0
365,2002,metropolitana,96.996,15.5,0.0
356,2002,atacama,4.310,15.3,0.0
357,2002,la_araucania,13.456,15.1,0.0
355,2002,maule,13.730,14.8,0.0
358,2002,ohiggins,11.978,14.8,0.0
366,2002,valparaiso,23.172,14.5,0.0
360,2002,biobio,27.990,14.2,0.0
367,2002,magallanes,2.243,14.0,0.0
353,2002,arica_parinacota,0.000,0.0,0.0
362,2002,nuble,0.000,0.0,0.0
364,2002,los_rios,0.000,0.0,0.0
368,2001,tarapaca,7.928,19.6,0.0
370,2001,antofagasta,8.709,18.4,0.0
379,2001,coquimbo,10.199,17.4,0.0
372,2001,atacama,4.603,16.6,0.0
377,2001,aysen,1.595,16.5,0.0
375,2001,los_lagos,17.507,16.3,0.0
381,2001,metropolitana,100.694,16.3,0.0
373,2001,la_araucania,13.657,15.5,0.0
374,2001,ohiggins,12.183,15.2,0.0
371,2001,maule,13.967,15.1,0.0
382,2001,valparaiso,23.870,15.1,0.0
376,2001,biobio,28.972,14.8,0.0
383,2001,magallanes,2.232,14.0,0.0
369,2001,arica_parinacota,0.000,0.0,0.0
378,2001,nuble,0.000,0.0,0.0
380,2001,los_rios,0.000,0.0,0.0
384,2000,tarapaca,8.070,20.2,0.0
386,2000,antofagasta,9.064,19.4,0.0
395,2000,coquimbo,10.221,17.7,0.0
397,2000,metropolitana,102.205,16.7,0.0
391,2000,los_lagos,17.457,16.4,0.0
388,2000,atacama,4.443,16.2,0.0
390,2000,ohiggins,12.533,15.9,0.0
393,2000,aysen,1.498,15.8,0.0
387,2000,maule,14.237,15.6,0.0
398,2000,valparaiso,24.325,15.6,0.0
389,2000,la_araucania,13.580,15.5,0.0
392,2000,biobio,28.908,14.9,0.0
399,2000,magallanes,2.352,14.9,0.0
385,2000,arica_parinacota,0.000,0.0,0.0
394,2000,nuble,0.000,0.0,0.0
396,2000,los_rios,0.000,0.0,0.0
400,1999,tarapaca,8.086,20.6,0.0
402,1999,antofagasta,9.199,19.9,0.0
411,1999,coquimbo,9.939,17.4,0.0
404,1999,atacama,4.641,17.2,0.0
413,1999,metropolitana,102.389,17.0,0.0
407,1999,los_lagos,17.242,16.4,0.0
406,1999,ohiggins,12.672,16.3,0.0
409,1999,aysen,1.530,16.3,0.0
405,1999,la_araucania,13.858,16.0,0.0
403,1999,maule,14.437,15.9,0.0
414,1999,valparaiso,24.546,15.9,0.0
408,1999,biobio,29.722,15.5,0.0
415,1999,magallanes,2.413,15.4,0.0
401,1999,arica_parinacota,0.000,0.0,0.0
410,1999,nuble,0.000,0.0,0.0
412,1999,los_rios,0.000,0.0,0.0
416,1998,tarapaca,8.157,21.1,0.0
418,1998,antofagasta,9.568,21.0,0.0
429,1998,metropolitana,105.471,17.8,0.0
427,1998,coquimbo,9.875,17.6,0.0
420,1998,atacama,4.621,17.5,0.0
423,1998,los_lagos,7.783,17.1,0.0
425,1998,aysen,1.566,17.0,0.0
421,1998,la_araucania,14.245,16.6,0.0
422,1998,ohiggins,12.787,16.6,0.0
419,1998,maule,14.812,16.5,0.0
430,1998,valparaiso,25.097,16.5,0.0
424,1998,biobio,30.635,16.2,0.0
431,1998,magallanes,2.488,16.0,0.0
417,1998,arica_parinacota,0.000,0.0,0.0
426,1998,nuble,0.000,0.0,0.0
428,1998,los_rios,0.000,0.0,0.0
434,1997,antofagasta,9.516,21.2,0.0
432,1997,tarapaca,8.009,21.1,0.0
443,1997,coquimbo,10.217,18.5,0.0
436,1997,atacama,4.698,18.1,0.0
445,1997,metropolitana,105.544,18.1,0.0
439,1997,los_lagos,18.365,17.9,0.0
438,1997,ohiggins,3.104,17.3,0.0
437,1997,la_araucania,14.589,17.2,0.0
440,1997,biobio,31.639,16.9,0.0
441,1997,aysen,1.536,16.9,0.0
435,1997,maule,14.962,16.8,0.0
446,1997,valparaiso,25.314,16.8,0.0
447,1997,magallanes,2.466,16.0,0.0
433,1997,arica_parinacota,0.000,0.0,0.0
442,1997,nuble,0.000,0.0,0.0
444,1997,los_rios,0.000,0.0,0.0
450,1996,antofagasta,9.763,22.0,0.0
448,1996,tarapaca,8.058,21.6,0.0
452,1996,atacama,5.071,19.9,0.0
459,1996,coquimbo,10.606,19.5,0.0
461,1996,metropolitana,107.586,18.8,0.0
455,1996,los_lagos,18.472,18.2,0.0
457,1996,aysen,1.585,17.7,0.0
451,1996,maule,15.489,17.6,0.0
454,1996,ohiggins,13.189,17.6,0.0
453,1996,la_araucania,14.882,17.4,0.0
456,1996,biobio,32.063,17.3,0.0
462,1996,valparaiso,25.781,17.3,0.0
463,1996,magallanes,2.548,16.7,0.0
449,1996,arica_parinacota,0.000,0.0,0.0
458,1996,nuble,0.000,0.0,0.0
460,1996,los_rios,0.000,0.0,0.0
466,1995,antofagasta,9.389,21.5,0.0
464,1995,tarapaca,7.746,21.1,0.0
468,1995,atacama,5.161,20.6,0.0
475,1995,coquimbo,10.619,19.8,0.0
477,1995,metropolitana,108.363,19.2,0.0
471,1995,los_lagos,18.394,18.3,0.0
470,1995,ohiggins,13.432,18.2,0.0
467,1995,maule,15.812,18.1,0.0
469,1995,la_araucania,14.667,17.8,0.0
478,1995,valparaiso,26.050,17.7,0.0
472,1995,biobio,32.251,17.6,0.0
473,1995,aysen,1.543,17.6,0.0
479,1995,magallanes,2.495,16.5,0.0
465,1995,arica_parinacota,0.000,0.0,0.0
474,1995,nuble,0.000,0.0,0.0
476,1995,los_rios,0.000,0.0,0.0
482,1994,antofagasta,9.562,22.2,0.0
480,1994,tarapaca,7.575,21.1,0.0
484,1994,atacama,5.165,21.1,0.0
491,1994,coquimbo,11.038,20.9,0.0
493,1994,metropolitana,110.774,20.0,0.0
489,1994,aysen,1.688,19.6,0.0
483,1994,maule,16.783,19.5,0.0
487,1994,los_lagos,19.015,19.2,0.0
486,1994,ohiggins,13.753,18.9,0.0
485,1994,la_araucania,15.236,18.7,0.0
494,1994,valparaiso,27.089,18.7,0.0
488,1994,biobio,33.573,18.6,0.0
495,1994,magallanes,2.515,16.8,0.0
481,1994,arica_parinacota,0.000,0.0,0.0
490,1994,nuble,0.000,0.0,0.0
492,1994,los_rios,0.000,0.0,0.0
498,1993,antofagasta,9.643,22.8,0.0
500,1993,atacama,3.377,22.4,0.0
496,1993,tarapaca,4.128,21.7,0.0
507,1993,coquimbo,11.243,21.7,0.0
509,1993,metropolitana,110.356,20.3,0.0
499,1993,maule,17.146,20.1,0.0
502,1993,ohiggins,14.079,19.7,0.0
505,1993,aysen,1.661,19.7,0.0
503,1993,los_lagos,19.076,19.5,0.0
504,1993,biobio,34.470,19.3,0.0
501,1993,la_araucania,15.487,19.2,0.0
510,1993,valparaiso,27.101,19.0,0.0
511,1993,magallanes,2.633,17.8,0.0
497,1993,arica_parinacota,0.000,0.0,0.0
506,1993,nuble,0.000,0.0,0.0
508,1993,los_rios,0.000,0.0,0.0

In [ ]:
madres_extranjeras_todos_los_ano = df_limpia.groupby(['ano', 'region'])[['porcentajes_madres_extranjeras', 'tasa_natalidad_1000', 'nacidos_vivos']].mean().reset_index().sort_values(by=['ano', 'porcentajes_madres_extranjeras'], ascending=[False, False])

madres_extranjeras_todos_los_ano

,ano,region,porcentajes_madres_extranjeras,tasa_natalidad_1000,nacidos_vivos
478,2022,tarapaca,47.9,12.7,5.023
464,2022,antofagasta,40.6,10.6,7.484
465,2022,arica_parinacota,38.1,11.3,2.916
475,2022,metropolitana,26.3,9.2,76.129
466,2022,atacama,20.1,10.3,3.265
477,2022,ohiggins,14.4,10.0,10.072
473,2022,magallanes,13.4,8.5,1.539
469,2022,coquimbo,12.8,9.4,8.019
479,2022,valparaiso,12.6,9.0,17.903
474,2022,maule,10.3,10.3,11.837
471,2022,los_lagos,7.9,9.9,8.955
467,2022,aysen,6.5,9.5,1.023
468,2022,biobio,5.9,9.6,16.115
476,2022,nuble,5.7,9.4,4.838
470,2022,la_araucania,3.9,10.2,10.405
472,2022,los_rios,3.0,9.3,3.780
462,2021,tarapaca,44.9,11.3,4.396
448,2021,antofagasta,37.4,9.6,6.748
449,2021,arica_parinacota,35.1,10.0,2.553
459,2021,metropolitana,24.5,8.9,73.062
450,2021,atacama,16.3,9.2,2.920
457,2021,magallanes,13.6,8.3,1.494
461,2021,ohiggins,11.4,9.3,9.258
463,2021,valparaiso,11.1,8.5,16.822
453,2021,coquimbo,10.8,8.9,7.564
458,2021,maule,8.9,9.4,10.689
455,2021,los_lagos,7.3,9.3,8.370
451,2021,aysen,5.7,9.1,982.000
452,2021,biobio,5.6,8.8,14.639
460,2021,nuble,5.0,8.7,4.481
456,2021,los_rios,3.6,8.4,3.435
454,2021,la_araucania,3.4,9.7,9.860
446,2020,tarapaca,39.2,12.3,4.709
432,2020,antofagasta,33.5,10.8,7.434
433,2020,arica_parinacota,31.7,11.5,2.886
443,2020,metropolitana,23.3,10.0,81.351
434,2020,atacama,14.0,10.3,3.247
441,2020,magallanes,12.5,9.2,1.638
445,2020,ohiggins,11.3,10.4,10.245
447,2020,valparaiso,10.8,9.4,18.427
437,2020,coquimbo,9.5,9.7,8.127
442,2020,maule,8.7,10.3,11.667
439,2020,los_lagos,7.0,10.1,8.958
435,2020,aysen,5.5,9.9,1.059
444,2020,nuble,5.2,9.6,4.885
436,2020,biobio,5.1,9.6,16.006
440,2020,los_rios,4.8,9.6,3.898
438,2020,la_araucania,3.8,10.3,10.441
430,2019,tarapaca,36.9,13.2,4.878
416,2019,antofagasta,31.1,11.7,7.770
417,2019,arica_parinacota,29.7,11.7,2.893
427,2019,metropolitana,22.9,11.4,89.770
418,2019,atacama,13.3,11.0,3.425
431,2019,valparaiso,11.8,10.1,19.619
429,2019,ohiggins,11.4,11.0,10.756
425,2019,magallanes,10.0,9.9,1.743
421,2019,coquimbo,9.6,10.6,8.666
426,2019,maule,9.6,11.2,12.496
423,2019,los_lagos,5.9,10.8,9.574
428,2019,nuble,4.6,10.0,5.065
419,2019,aysen,4.5,10.5,1.120
420,2019,biobio,4.4,10.4,17.107
424,2019,los_rios,4.2,9.9,4.004
422,2019,la_araucania,3.7,11.2,11.302
414,2018,tarapaca,33.7,14.0,4.955
400,2018,antofagasta,28.5,12.5,8.049
401,2018,arica_parinacota,22.8,12.2,2.958
411,2018,metropolitana,21.0,12.5,95.834
402,2018,atacama,10.0,12.2,3.730
415,2018,valparaiso,9.7,11.0,21.002
413,2018,ohiggins,9.4,11.6,11.248
409,2018,magallanes,8.1,10.2,1.757
410,2018,maule,7.9,11.8,13.070
405,2018,coquimbo,7.6,11.3,9.095
412,2018,nuble,4.6,10.6,5.324
403,2018,aysen,4.1,11.9,1.258
407,2018,los_lagos,4.1,11.3,9.921
408,2018,los_rios,3.3,10.3,4.106
406,2018,la_araucania,3.2,11.8,11.772
404,2018,biobio,2.7,10.7,17.652
398,2017,tarapaca,31.7,14.9,5.081
384,2017,antofagasta,24.8,13.5,8.396
385,2017,arica_parinacota,21.1,12.8,3.037
395,2017,metropolitana,14.4,12.4,92.727
386,2017,atacama,7.0,12.9,3.929
393,2017,magallanes,5.0,11.0,1.883
389,2017,coquimbo,4.0,11.6,9.215
399,2017,valparaiso,3.0,10.8,20.357
397,2017,ohiggins,2.9,11.4,10.887
387,2017,aysen,2.5,11.5,1.215
394,2017,maule,2.0,11.6,12.632
388,2017,biobio,1.5,11.1,18.175
391,2017,los_lagos,1.5,11.6,10.046
396,2017,nuble,1.5,10.7,5.333
390,2017,la_araucania,1.4,12.1,12.005
392,2017,los_rios,1.1,10.7,4.268
382,2016,tarapaca,27.5,15.9,5.419
368,2016,antofagasta,22.5,14.7,9.214
374,2016,la_araucania,20.0,12.6,12.534
369,2016,arica_parinacota,16.9,13.2,3.169
379,2016,metropolitana,9.7,13.1,96.616
370,2016,atacama,6.1,13.4,4.230
377,2016,magallanes,3.9,11.3,1.873
373,2016,coquimbo,2.4,13.0,10.126
383,2016,valparaiso,2.2,12.1,22.165
371,2016,aysen,1.5,13.0,1.408
381,2016,ohiggins,1.5,12.4,11.416
376,2016,los_rios,1.0,11.2,4.532
375,2016,los_lagos,0.9,12.8,10.787
378,2016,maule,0.9,12.6,13.225
372,2016,biobio,0.8,11.8,19.582
380,2016,nuble,0.8,11.2,5.453
366,2015,tarapaca,18.6,17.1,5.712
352,2015,antofagasta,16.9,15.9,9.885
353,2015,arica_parinacota,13.2,14.3,3.414
363,2015,metropolitana,6.5,13.9,101.087
354,2015,atacama,4.9,14.3,4.466
361,2015,magallanes,2.9,12.4,2.032
357,2015,coquimbo,1.8,13.0,11.010
355,2015,aysen,1.6,13.1,1.413
367,2015,valparaiso,1.5,13.0,23.598
359,2015,los_lagos,1.0,13.3,11.158
362,2015,maule,0.8,13.5,14.068
360,2015,los_rios,0.7,11.6,4.664
356,2015,biobio,0.6,12.7,21.023
358,2015,la_araucania,0.6,13.5,13.324
364,2015,nuble,0.6,11.9,5.766
365,2015,ohiggins,0.1,13.2,12.050
336,2014,antofagasta,0.0,16.7,10.191
337,2014,arica_parinacota,0.0,15.1,3.546
338,2014,atacama,0.0,16.4,5.014
339,2014,aysen,0.0,14.4,1.535
340,2014,biobio,0.0,13.2,21.599
341,2014,coquimbo,0.0,15.3,11.577
342,2014,la_araucania,0.0,13.7,13.313
343,2014,los_lagos,0.0,13.7,11.380
344,2014,los_rios,0.0,12.6,5.063
345,2014,magallanes,0.0,12.9,2.104
346,2014,maule,0.0,13.9,14.345
347,2014,metropolitana,0.0,14.3,103.059
348,2014,nuble,0.0,11.9,5.899
349,2014,ohiggins,0.0,13.7,12.412
350,2014,tarapaca,0.0,17.8,5.835
351,2014,valparaiso,0.0,13.4,24.125
320,2013,antofagasta,0.0,16.4,9.841
321,2013,arica_parinacota,0.0,15.2,3.504
322,2013,atacama,0.0,16.0,4.849
323,2013,aysen,0.0,13.6,1.440
324,2013,biobio,0.0,12.7,20.714
325,2013,coquimbo,0.0,15.2,11.343
326,2013,la_araucania,0.0,13.2,12.877
327,2013,los_lagos,0.0,13.6,11.191
328,2013,los_rios,0.0,12.2,4.814
329,2013,magallanes,0.0,12.6,2.041
330,2013,maule,0.0,13.4,13.714
331,2013,metropolitana,0.0,13.9,99.081
332,2013,nuble,0.0,11.7,5.590
333,2013,ohiggins,0.0,13.5,12.113
334,2013,tarapaca,0.0,18.1,5.766
335,2013,valparaiso,0.0,13.0,23.127
304,2012,antofagasta,0.0,16.6,9.817
305,2012,arica_parinacota,0.0,15.7,3.558
306,2012,atacama,0.0,16.2,4.855
307,2012,aysen,0.0,14.7,1.540
308,2012,biobio,0.0,12.9,20.997
309,2012,coquimbo,0.0,15.3,11.217
310,2012,la_araucania,0.0,13.4,13.024
311,2012,los_lagos,0.0,13.7,11.287
312,2012,los_rios,0.0,12.9,5.124
313,2012,magallanes,0.0,13.0,2.108
314,2012,maule,0.0,13.2,13.429
315,2012,metropolitana,0.0,14.1,99.488
316,2012,nuble,0.0,12.0,5.732
317,2012,ohiggins,0.0,13.6,12.119
318,2012,tarapaca,0.0,18.4,5.721
319,2012,valparaiso,0.0,13.3,23.619
288,2011,antofagasta,0.0,17.2,9.932
289,2011,arica_parinacota,0.0,20.0,3.640
290,2011,atacama,0.0,18.2,5.116
291,2011,aysen,0.0,14.6,1.545
292,2011,biobio,0.0,13.7,21.986
293,2011,coquimbo,0.0,15.4,11.148
294,2011,la_araucania,0.0,13.8,13.295
295,2011,los_lagos,0.0,14.2,11.911
296,2011,los_rios,0.0,13.7,5.176
297,2011,magallanes,0.0,13.4,2.118
298,2011,maule,0.0,13.5,13.640
299,2011,metropolitana,0.0,14.5,100.415
300,2011,nuble,0.0,0.0,0.000
301,2011,ohiggins,0.0,13.8,12.189
302,2011,tarapaca,0.0,18.1,5.753
303,2011,valparaiso,0.0,13.3,23.568
272,2010,antofagasta,0.0,17.5,10.016
273,2010,arica_parinacota,0.0,20.0,3.646
274,2010,atacama,0.0,18.1,5.069
275,2010,aysen,0.0,15.7,1.636
276,2010,biobio,0.0,13.9,22.293
277,2010,coquimbo,0.0,15.6,11.225
278,2010,la_araucania,0.0,13.8,13.367
279,2010,los_lagos,0.0,14.9,12.413
280,2010,los_rios,0.0,14.4,5.433
281,2010,magallanes,0.0,14.2,2.243
282,2010,maule,0.0,14.0,14.103
283,2010,metropolitana,0.0,14.7,101.047
284,2010,nuble,0.0,0.0,0.000
285,2010,ohiggins,0.0,14.4,12.723
286,2010,tarapaca,0.0,18.0,5.637
287,2010,valparaiso,0.0,13.5,23.788
256,2009,antofagasta,0.0,17.7,9.988
257,2009,arica_parinacota,0.0,19.1,3.559
258,2009,atacama,0.0,18.8,5.194
259,2009,aysen,0.0,16.4,1.687
260,2009,biobio,0.0,14.1,28.313
261,2009,coquimbo,0.0,15.3,10.801
262,2009,la_araucania,0.0,14.2,13.546
263,2009,los_lagos,0.0,15.9,13.072
264,2009,los_rios,0.0,14.2,5.349
265,2009,magallanes,0.0,14.1,2.217
266,2009,maule,0.0,14.2,14.108
267,2009,metropolitana,0.0,15.1,102.248
268,2009,nuble,0.0,0.0,0.000
269,2009,ohiggins,0.0,14.6,12.731
270,2009,tarapaca,0.0,18.7,5.692
271,2009,valparaiso,0.0,13.7,23.735
240,2008,antofagasta,0.0,17.4,9.706
241,2008,arica_parinacota,0.0,18.3,3.364
242,2008,atacama,0.0,17.5,4.803
243,2008,aysen,0.0,17.2,1.733
244,2008,biobio,0.0,13.9,27.779
245,2008,coquimbo,0.0,15.1,10.447
246,2008,la_araucania,0.0,14.3,13.494
247,2008,los_lagos,0.0,15.7,12.772
248,2008,los_rios,0.0,14.2,5.306
249,2008,magallanes,0.0,14.5,2.264
250,2008,maule,0.0,14.2,14.045
251,2008,metropolitana,0.0,14.9,99.873
252,2008,nuble,0.0,0.0,0.000
253,2008,ohiggins,0.0,14.7,12.592
254,2008,tarapaca,0.0,17.8,5.287
255,2008,valparaiso,0.0,13.5,23.116
224,2007,antofagasta,0.0,17.1,9.419
225,2007,arica_parinacota,0.0,16.8,3.158
226,2007,atacama,0.0,17.3,4.720
227,2007,aysen,0.0,16.5,1.679
228,2007,biobio,0.0,14.0,27.682
229,2007,coquimbo,0.0,14.4,9.794
230,2007,la_araucania,0.0,14.3,13.418
231,2007,los_lagos,0.0,15.4,12.335
232,2007,los_rios,0.0,13.9,5.154
233,2007,magallanes,0.0,14.0,2.173
234,2007,maule,0.0,13.9,13.566
235,2007,metropolitana,0.0,14.7,97.596
236,2007,nuble,0.0,0.0,0.000
237,2007,ohiggins,0.0,14.3,12.199
238,2007,tarapaca,0.0,17.1,5.017
239,2007,valparaiso,0.0,13.4,22.659
208,2006,antofagasta,0.0,16.5,8.975
209,2006,arica_parinacota,0.0,16.6,3.099
210,2006,atacama,0.0,17.1,4.648
211,2006,aysen,0.0,16.1,1.563
212,2006,biobio,0.0,13.7,27.028
213,2006,coquimbo,0.0,13.9,9.372
214,2006,la_araucania,0.0,14.0,13.016
215,2006,los_lagos,0.0,14.9,11.758
216,2006,los_rios,0.0,13.8,5.155
217,2006,magallanes,0.0,14.0,2.127
218,2006,maule,0.0,13.4,13.099
219,2006,metropolitana,0.0,14.3,93.593
220,2006,nuble,0.0,0.0,0.000
221,2006,ohiggins,0.0,13.6,11.517
222,2006,tarapaca,0.0,16.7,4.761
223,2006,valparaiso,0.0,13.0,21.672
192,2005,antofagasta,0.0,16.6,9.000
193,2005,arica_parinacota,0.0,17.2,3.287
194,2005,atacama,0.0,16.7,4.523
195,2005,aysen,0.0,16.7,1.662
196,2005,biobio,0.0,14.3,28.170
197,2005,coquimbo,0.0,15.0,9.992
198,2005,la_araucania,0.0,14.6,13.545
199,2005,los_lagos,0.0,16.1,12.642
200,2005,los_rios,0.0,14.4,5.355
201,2005,magallanes,0.0,14.6,2.271
202,2005,maule,0.0,14.5,14.008
203,2005,metropolitana,0.0,14.9,97.653
204,2005,nuble,0.0,0.0,0.000
205,2005,ohiggins,0.0,14.8,12.408
206,2005,tarapaca,0.0,18.0,5.024
207,2005,valparaiso,0.0,14.1,23.409
176,2004,antofagasta,0.0,17.0,9.052
177,2004,arica_parinacota,0.0,17.1,3.270
178,2004,atacama,0.0,16.5,4.434
179,2004,aysen,0.0,17.0,1.674
180,2004,biobio,0.0,14.5,28.268
181,2004,coquimbo,0.0,14.8,9.691
182,2004,la_araucania,0.0,15.0,13.819
183,2004,los_lagos,0.0,16.1,12.442
184,2004,los_rios,0.0,14.6,5.410
185,2004,magallanes,0.0,14.1,2.195
186,2004,maule,0.0,14.5,13.892
187,2004,metropolitana,0.0,15.2,97.982
188,2004,nuble,0.0,0.0,0.000
189,2004,ohiggins,0.0,14.9,13.382
190,2004,tarapaca,0.0,17.7,4.821
191,2004,valparaiso,0.0,14.1,23.118
160,2003,antofagasta,0.0,17.8,8.663
161,2003,arica_parinacota,0.0,0.0,0.000
162,2003,atacama,0.0,15.4,4.407
163,2003,aysen,0.0,15.9,1.578
164,2003,biobio,0.0,14.1,28.040
165,2003,coquimbo,0.0,15.7,9.459
166,2003,la_araucania,0.0,14.4,13.013
167,2003,los_lagos,0.0,15.5,16.935
168,2003,los_rios,0.0,0.0,0.000
169,2003,magallanes,0.0,13.6,2.198
170,2003,maule,0.0,14.3,13.453
171,2003,metropolitana,0.0,14.9,94.728
172,2003,nuble,0.0,0.0,0.000
173,2003,ohiggins,0.0,14.4,11.799
174,2003,tarapaca,0.0,18.5,7.732
175,2003,valparaiso,0.0,13.9,22.481
144,2002,antofagasta,0.0,18.4,8.842
145,2002,arica_parinacota,0.0,0.0,0.000
146,2002,atacama,0.0,15.3,4.310
147,2002,aysen,0.0,16.2,1.579
148,2002,biobio,0.0,14.2,27.990
149,2002,coquimbo,0.0,16.2,9.608
150,2002,la_araucania,0.0,15.1,13.456
151,2002,los_lagos,0.0,16.2,17.506
152,2002,los_rios,0.0,0.0,0.000
153,2002,magallanes,0.0,14.0,2.243
154,2002,maule,0.0,14.8,13.730
155,2002,metropolitana,0.0,15.5,96.996
156,2002,nuble,0.0,0.0,0.000
157,2002,ohiggins,0.0,14.8,11.978
158,2002,tarapaca,0.0,18.4,7.571
159,2002,valparaiso,0.0,14.5,23.172
128,2001,antofagasta,0.0,18.4,8.709
129,2001,arica_parinacota,0.0,0.0,0.000
130,2001,atacama,0.0,16.6,4.603
131,2001,aysen,0.0,16.5,1.595
132,2001,biobio,0.0,14.8,28.972
133,2001,coquimbo,0.0,17.4,10.199
134,2001,la_araucania,0.0,15.5,13.657
135,2001,los_lagos,0.0,16.3,17.507
136,2001,los_rios,0.0,0.0,0.000
137,2001,magallanes,0.0,14.0,2.232
138,2001,maule,0.0,15.1,13.967
139,2001,metropolitana,0.0,16.3,100.694
140,2001,nuble,0.0,0.0,0.000
141,2001,ohiggins,0.0,15.2,12.183
142,2001,tarapaca,0.0,19.6,7.928
143,2001,valparaiso,0.0,15.1,23.870
112,2000,antofagasta,0.0,19.4,9.064
113,2000,arica_parinacota,0.0,0.0,0.000
114,2000,atacama,0.0,16.2,4.443
115,2000,aysen,0.0,15.8,1.498
116,2000,biobio,0.0,14.9,28.908
117,2000,coquimbo,0.0,17.7,10.221
118,2000,la_araucania,0.0,15.5,13.580
119,2000,los_lagos,0.0,16.4,17.457
120,2000,los_rios,0.0,0.0,0.000
121,2000,magallanes,0.0,14.9,2.352
122,2000,maule,0.0,15.6,14.237
123,2000,metropolitana,0.0,16.7,102.205
124,2000,nuble,0.0,0.0,0.000
125,2000,ohiggins,0.0,15.9,12.533
126,2000,tarapaca,0.0,20.2,8.070
127,2000,valparaiso,0.0,15.6,24.325
96,1999,antofagasta,0.0,19.9,9.199
97,1999,arica_parinacota,0.0,0.0,0.000
98,1999,atacama,0.0,17.2,4.641
99,1999,aysen,0.0,16.3,1.530
100,1999,biobio,0.0,15.5,29.722
101,1999,coquimbo,0.0,17.4,9.939
102,1999,la_araucania,0.0,16.0,13.858
103,1999,los_lagos,0.0,16.4,17.242
104,1999,los_rios,0.0,0.0,0.000
105,1999,magallanes,0.0,15.4,2.413
106,1999,maule,0.0,15.9,14.437
107,1999,metropolitana,0.0,17.0,102.389
108,1999,nuble,0.0,0.0,0.000
109,1999,ohiggins,0.0,16.3,12.672
110,1999,tarapaca,0.0,20.6,8.086
111,1999,valparaiso,0.0,15.9,24.546
80,1998,antofagasta,0.0,21.0,9.568
81,1998,arica_parinacota,0.0,0.0,0.000
82,1998,atacama,0.0,17.5,4.621
83,1998,aysen,0.0,17.0,1.566
84,1998,biobio,0.0,16.2,30.635
85,1998,coquimbo,0.0,17.6,9.875
86,1998,la_araucania,0.0,16.6,14.245
87,1998,los_lagos,0.0,17.1,7.783
88,1998,los_rios,0.0,0.0,0.000
89,1998,magallanes,0.0,16.0,2.488
90,1998,maule,0.0,16.5,14.812
91,1998,metropolitana,0.0,17.8,105.471
92,1998,nuble,0.0,0.0,0.000
93,1998,ohiggins,0.0,16.6,12.787
94,1998,tarapaca,0.0,21.1,8.157
95,1998,valparaiso,0.0,16.5,25.097
64,1997,antofagasta,0.0,21.2,9.516
65,1997,arica_parinacota,0.0,0.0,0.000
66,1997,atacama,0.0,18.1,4.698
67,1997,aysen,0.0,16.9,1.536
68,1997,biobio,0.0,16.9,31.639
69,1997,coquimbo,0.0,18.5,10.217
70,1997,la_araucania,0.0,17.2,14.589
71,1997,los_lagos,0.0,17.9,18.365
72,1997,los_rios,0.0,0.0,0.000
73,1997,magallanes,0.0,16.0,2.466
74,1997,maule,0.0,16.8,14.962
75,1997,metropolitana,0.0,18.1,105.544
76,1997,nuble,0.0,0.0,0.000
77,1997,ohiggins,0.0,17.3,3.104
78,1997,tarapaca,0.0,21.1,8.009
79,1997,valparaiso,0.0,16.8,25.314
48,1996,antofagasta,0.0,22.0,9.763
49,1996,arica_parinacota,0.0,0.0,0.000
50,1996,atacama,0.0,19.9,5.071
51,1996,aysen,0.0,17.7,1.585
52,1996,biobio,0.0,17.3,32.063
53,1996,coquimbo,0.0,19.5,10.606
54,1996,la_araucania,0.0,17.4,14.882
55,1996,los_lagos,0.0,18.2,18.472
56,1996,los_rios,0.0,0.0,0.000
57,1996,magallanes,0.0,16.7,2.548
58,1996,maule,0.0,17.6,15.489
59,1996,metropolitana,0.0,18.8,107.586
60,1996,nuble,0.0,0.0,0.000
61,1996,ohiggins,0.0,17.6,13.189
62,1996,tarapaca,0.0,21.6,8.058
63,1996,valparaiso,0.0,17.3,25.781
32,1995,antofagasta,0.0,21.5,9.389
33,1995,arica_parinacota,0.0,0.0,0.000
34,1995,atacama,0.0,20.6,5.161
35,1995,aysen,0.0,17.6,1.543
36,1995,biobio,0.0,17.6,32.251
37,1995,coquimbo,0.0,19.8,10.619
38,1995,la_araucania,0.0,17.8,14.667
39,1995,los_lagos,0.0,18.3,18.394
40,1995,los_rios,0.0,0.0,0.000
41,1995,magallanes,0.0,16.5,2.495
42,1995,maule,0.0,18.1,15.812
43,1995,metropolitana,0.0,19.2,108.363
44,1995,nuble,0.0,0.0,0.000
45,1995,ohiggins,0.0,18.2,13.432
46,1995,tarapaca,0.0,21.1,7.746
47,1995,valparaiso,0.0,17.7,26.050
16,1994,antofagasta,0.0,22.2,9.562
17,1994,arica_parinacota,0.0,0.0,0.000
18,1994,atacama,0.0,21.1,5.165
19,1994,aysen,0.0,19.6,1.688
20,1994,biobio,0.0,18.6,33.573
21,1994,coquimbo,0.0,20.9,11.038
22,1994,la_araucania,0.0,18.7,15.236
23,1994,los_lagos,0.0,19.2,19.015
24,1994,los_rios,0.0,0.0,0.000
25,1994,magallanes,0.0,16.8,2.515
26,1994,maule,0.0,19.5,16.783
27,1994,metropolitana,0.0,20.0,110.774
28,1994,nuble,0.0,0.0,0.000
29,1994,ohiggins,0.0,18.9,13.753
30,1994,tarapaca,0.0,21.1,7.575
31,1994,valparaiso,0.0,18.7,27.089
0,1993,antofagasta,0.0,22.8,9.643
1,1993,arica_parinacota,0.0,0.0,0.000
2,1993,atacama,0.0,22.4,3.377
3,1993,aysen,0.0,19.7,1.661
4,1993,biobio,0.0,19.3,34.470
5,1993,coquimbo,0.0,21.7,11.243
6,1993,la_araucania,0.0,19.2,15.487
7,1993,los_lagos,0.0,19.5,19.076
8,1993,los_rios,0.0,0.0,0.000
9,1993,magallanes,0.0,17.8,2.633
10,1993,maule,0.0,20.1,17.146
11,1993,metropolitana,0.0,20.3,110.356
12,1993,nuble,0.0,0.0,0.000
13,1993,ohiggins,0.0,19.7,14.079
14,1993,tarapaca,0.0,21.7,4.128
15,1993,valparaiso,0.0,19.0,27.101

In [ ]:
df_2015 = df_limpia[df_limpia['ano'] == 2015]
df_2015[["region", "tasa_natalidad_1000", "porcentajes_madres_extranjeras"]].sort_values(by="porcentajes_madres_extranjeras", ascending=False)

               region tasa_natalidad_1000 porcentajes_madres_extranjeras
144          tarapaca                17.1                           18.6
146       antofagasta                15.9                           16.9
145  arica_parinacota                14.3                           13.2
157     metropolitana                13.9                            6.5
148           atacama                14.3                            4.9
159        magallanes                12.4                            2.9
155          coquimbo                13.0                            1.8
153             aysen                13.1                            1.6
158        valparaiso                13.0                            1.5
151         los_lagos                13.3                            1.0
147             maule                13.5                            0.8
156          los_rios                11.6                            0.7
149      la_araucania                13.5                            0.6
152            biobio                12.7                            0.6
154             nuble                11.9                            0.6
150          ohiggins                13.2                            0.1

In [ ]:
df_2022 = df_limpia[df_limpia['ano'] == 2022]
df_2022[["region", "tasa_natalidad_1000", "porcentajes_madres_extranjeras"]].sort_values(by="porcentajes_madres_extranjeras", ascending=False)

              region tasa_natalidad_1000 porcentajes_madres_extranjeras
32          tarapaca                12.7                           47.9
34       antofagasta                10.6                           40.6
33  arica_parinacota                11.3                           38.1
45     metropolitana                 9.2                           26.3
36           atacama                10.3                           20.1
38          ohiggins                10.0                           14.4
47        magallanes                 8.5                           13.4
43          coquimbo                 9.4                           12.8
46        valparaiso                 9.0                           12.6
35             maule                10.3                           10.3
39         los_lagos                 9.9                            7.9
41             aysen                 9.5                            6.5
40            biobio                 9.6                            5.9
42             nuble                 9.4                            5.7
37      la_araucania                10.2                            3.9
44          los_rios                 9.3                            3.0

In [ ]:
tarapaca = df_limpia[df_limpia['region'] == 'tarapaca']
tarapaca = tarapaca[['ano', 'region', 'porcentajes_madres_extranjeras', 'tasa_natalidad_1000', 'nacidos_vivos']]

display(tarapaca)

,ano,region,porcentajes_madres_extranjeras,tasa_natalidad_1000,nacidos_vivos
32,2022,tarapaca,47.9,12.7,5.023
48,2021,tarapaca,44.9,11.3,4.396
64,2020,tarapaca,39.2,12.3,4.709
80,2019,tarapaca,36.9,13.2,4.878
96,2018,tarapaca,33.7,14.0,4.955
112,2017,tarapaca,31.7,14.9,5.081
128,2016,tarapaca,27.5,15.9,5.419
144,2015,tarapaca,18.6,17.1,5.712
160,2014,tarapaca,0.0,17.8,5.835
176,2013,tarapaca,0.0,18.1,5.766
192,2012,tarapaca,0.0,18.4,5.721
208,2011,tarapaca,0.0,18.1,5.753
224,2010,tarapaca,0.0,18.0,5.637
240,2009,tarapaca,0.0,18.7,5.692
256,2008,tarapaca,0.0,17.8,5.287
272,2007,tarapaca,0.0,17.1,5.017
288,2006,tarapaca,0.0,16.7,4.761
304,2005,tarapaca,0.0,18.0,5.024
320,2004,tarapaca,0.0,17.7,4.821
336,2003,tarapaca,0.0,18.5,7.732
352,2002,tarapaca,0.0,18.4,7.571
368,2001,tarapaca,0.0,19.6,7.928
384,2000,tarapaca,0.0,20.2,8.070
400,1999,tarapaca,0.0,20.6,8.086
416,1998,tarapaca,0.0,21.1,8.157
432,1997,tarapaca,0.0,21.1,8.009
448,1996,tarapaca,0.0,21.6,8.058
464,1995,tarapaca,0.0,21.1,7.746
480,1994,tarapaca,0.0,21.1,7.575
496,1993,tarapaca,0.0,21.7,4.128

In [ ]:
antofagasta = df_limpia[df_limpia['region'] == 'antofagasta']
antofagasta = antofagasta[['ano', 'region', 'porcentajes_madres_extranjeras', 'tasa_natalidad_1000', 'nacidos_vivos']]

display(antofagasta)

,ano,region,porcentajes_madres_extranjeras,tasa_natalidad_1000,nacidos_vivos
34,2022,antofagasta,40.6,10.6,7.484
50,2021,antofagasta,37.4,9.6,6.748
66,2020,antofagasta,33.5,10.8,7.434
82,2019,antofagasta,31.1,11.7,7.770
98,2018,antofagasta,28.5,12.5,8.049
114,2017,antofagasta,24.8,13.5,8.396
130,2016,antofagasta,22.5,14.7,9.214
146,2015,antofagasta,16.9,15.9,9.885
162,2014,antofagasta,0.0,16.7,10.191
178,2013,antofagasta,0.0,16.4,9.841
194,2012,antofagasta,0.0,16.6,9.817
210,2011,antofagasta,0.0,17.2,9.932
226,2010,antofagasta,0.0,17.5,10.016
242,2009,antofagasta,0.0,17.7,9.988
258,2008,antofagasta,0.0,17.4,9.706
274,2007,antofagasta,0.0,17.1,9.419
290,2006,antofagasta,0.0,16.5,8.975
306,2005,antofagasta,0.0,16.6,9.000
322,2004,antofagasta,0.0,17.0,9.052
338,2003,antofagasta,0.0,17.8,8.663
354,2002,antofagasta,0.0,18.4,8.842
370,2001,antofagasta,0.0,18.4,8.709
386,2000,antofagasta,0.0,19.4,9.064
402,1999,antofagasta,0.0,19.9,9.199
418,1998,antofagasta,0.0,21.0,9.568
434,1997,antofagasta,0.0,21.2,9.516
450,1996,antofagasta,0.0,22.0,9.763
466,1995,antofagasta,0.0,21.5,9.389
482,1994,antofagasta,0.0,22.2,9.562
498,1993,antofagasta,0.0,22.8,9.643

In [ ]:
ranking_madres_extranjeras = df_limpia.sort_values(by=["ano", "porcentajes_madres_extranjeras"], ascending=[True, False])
display(ranking_madres_extranjeras[["ano", "region", "porcentajes_madres_extranjeras", "tasa_natalidad_1000"]])

      ano            region porcentajes_madres_extranjeras tasa_natalidad_1000
496  1993          tarapaca                            0.0                21.7
497  1993  arica_parinacota                            0.0                 0.0
498  1993       antofagasta                            0.0                22.8
499  1993             maule                            0.0                20.1
500  1993           atacama                            0.0                22.4
501  1993      la_araucania                            0.0                19.2
502  1993          ohiggins                            0.0                19.7
503  1993         los_lagos                            0.0                19.5
504  1993            biobio                            0.0                19.3
505  1993             aysen                            0.0                19.7
506  1993             nuble                            0.0                 0.0
507  1993          coquimbo                            0.0                21.7
508  1993          los_rios                            0.0                 0.0
509  1993     metropolitana                            0.0                20.3
510  1993        valparaiso                            0.0                19.0
511  1993        magallanes                            0.0                17.8
480  1994          tarapaca                            0.0                21.1
481  1994  arica_parinacota                            0.0                 0.0
482  1994       antofagasta                            0.0                22.2
483  1994             maule                            0.0                19.5
484  1994           atacama                            0.0                21.1
485  1994      la_araucania                            0.0                18.7
486  1994          ohiggins                            0.0                18.9
487  1994         los_lagos                            0.0                19.2
488  1994            biobio                            0.0                18.6
489  1994             aysen                            0.0                19.6
490  1994             nuble                            0.0                 0.0
491  1994          coquimbo                            0.0                20.9
492  1994          los_rios                            0.0                 0.0
493  1994     metropolitana                            0.0                20.0
494  1994        valparaiso                            0.0                18.7
495  1994        magallanes                            0.0                16.8
464  1995          tarapaca                            0.0                21.1
465  1995  arica_parinacota                            0.0                 0.0
466  1995       antofagasta                            0.0                21.5
467  1995             maule                            0.0                18.1
468  1995           atacama                            0.0                20.6
469  1995      la_araucania                            0.0                17.8
470  1995          ohiggins                            0.0                18.2
471  1995         los_lagos                            0.0                18.3
472  1995            biobio                            0.0                17.6
473  1995             aysen                            0.0                17.6
474  1995             nuble                            0.0                 0.0
475  1995          coquimbo                            0.0                19.8
476  1995          los_rios                            0.0                 0.0
477  1995     metropolitana                            0.0                19.2
478  1995        valparaiso                            0.0                17.7
479  1995        magallanes                            0.0                16.5
448  1996          tarapaca                            0.0                21.6
449  1996  arica_parinacota                            0.0                 0.0
450  1996       antofagasta                            0.0                22.0
451  1996             maule                            0.0                17.6
452  1996           atacama                            0.0                19.9
453  1996      la_araucania                            0.0                17.4
454  1996          ohiggins                            0.0                17.6
455  1996         los_lagos                            0.0                18.2
456  1996            biobio                            0.0                17.3
457  1996             aysen                            0.0                17.7
458  1996             nuble                            0.0                 0.0
459  1996          coquimbo                            0.0                19.5
460  1996          los_rios                            0.0                 0.0
461  1996     metropolitana                            0.0                18.8
462  1996        valparaiso                            0.0                17.3
463  1996        magallanes                            0.0                16.7
432  1997          tarapaca                            0.0                21.1
433  1997  arica_parinacota                            0.0                 0.0
434  1997       antofagasta                            0.0                21.2
435  1997             maule                            0.0                16.8
436  1997           atacama                            0.0                18.1
437  1997      la_araucania                            0.0                17.2
438  1997          ohiggins                            0.0                17.3
439  1997         los_lagos                            0.0                17.9
440  1997            biobio                            0.0                16.9
441  1997             aysen                            0.0                16.9
442  1997             nuble                            0.0                 0.0
443  1997          coquimbo                            0.0                18.5
444  1997          los_rios                            0.0                 0.0
445  1997     metropolitana                            0.0                18.1
446  1997        valparaiso                            0.0                16.8
447  1997        magallanes                            0.0                16.0
416  1998          tarapaca                            0.0                21.1
417  1998  arica_parinacota                            0.0                 0.0
418  1998       antofagasta                            0.0                21.0
419  1998             maule                            0.0                16.5
420  1998           atacama                            0.0                17.5
421  1998      la_araucania                            0.0                16.6
422  1998          ohiggins                            0.0                16.6
423  1998         los_lagos                            0.0                17.1
424  1998            biobio                            0.0                16.2
425  1998             aysen                            0.0                17.0
426  1998             nuble                            0.0                 0.0
427  1998          coquimbo                            0.0                17.6
428  1998          los_rios                            0.0                 0.0
429  1998     metropolitana                            0.0                17.8
430  1998        valparaiso                            0.0                16.5
431  1998        magallanes                            0.0                16.0
400  1999          tarapaca                            0.0                20.6
401  1999  arica_parinacota                            0.0                 0.0
402  1999       antofagasta                            0.0                19.9
403  1999             maule                            0.0                15.9
404  1999           atacama                            0.0                17.2
405  1999      la_araucania                            0.0                16.0
406  1999          ohiggins                            0.0                16.3
407  1999         los_lagos                            0.0                16.4
408  1999            biobio                            0.0                15.5
409  1999             aysen                            0.0                16.3
410  1999             nuble                            0.0                 0.0
411  1999          coquimbo                            0.0                17.4
412  1999          los_rios                            0.0                 0.0
413  1999     metropolitana                            0.0                17.0
414  1999        valparaiso                            0.0                15.9
415  1999        magallanes                            0.0                15.4
384  2000          tarapaca                            0.0                20.2
385  2000  arica_parinacota                            0.0                 0.0
386  2000       antofagasta                            0.0                19.4
387  2000             maule                            0.0                15.6
388  2000           atacama                            0.0                16.2
389  2000      la_araucania                            0.0                15.5
390  2000          ohiggins                            0.0                15.9
391  2000         los_lagos                            0.0                16.4
392  2000            biobio                            0.0                14.9
393  2000             aysen                            0.0                15.8
394  2000             nuble                            0.0                 0.0
395  2000          coquimbo                            0.0                17.7
396  2000          los_rios                            0.0                 0.0
397  2000     metropolitana                            0.0                16.7
398  2000        valparaiso                            0.0                15.6
399  2000        magallanes                            0.0                14.9
368  2001          tarapaca                            0.0                19.6
369  2001  arica_parinacota                            0.0                 0.0
370  2001       antofagasta                            0.0                18.4
371  2001             maule                            0.0                15.1
372  2001           atacama                            0.0                16.6
373  2001      la_araucania                            0.0                15.5
374  2001          ohiggins                            0.0                15.2
375  2001         los_lagos                            0.0                16.3
376  2001            biobio                            0.0                14.8
377  2001             aysen                            0.0                16.5
378  2001             nuble                            0.0                 0.0
379  2001          coquimbo                            0.0                17.4
380  2001          los_rios                            0.0                 0.0
381  2001     metropolitana                            0.0                16.3
382  2001        valparaiso                            0.0                15.1
383  2001        magallanes                            0.0                14.0
352  2002          tarapaca                            0.0                18.4
353  2002  arica_parinacota                            0.0                 0.0
354  2002       antofagasta                            0.0                18.4
355  2002             maule                            0.0                14.8
356  2002           atacama                            0.0                15.3
357  2002      la_araucania                            0.0                15.1
358  2002          ohiggins                            0.0                14.8
359  2002         los_lagos                            0.0                16.2
360  2002            biobio                            0.0                14.2
361  2002             aysen                            0.0                16.2
362  2002             nuble                            0.0                 0.0
363  2002          coquimbo                            0.0                16.2
364  2002          los_rios                            0.0                 0.0
365  2002     metropolitana                            0.0                15.5
366  2002        valparaiso                            0.0                14.5
367  2002        magallanes                            0.0                14.0
336  2003          tarapaca                            0.0                18.5
337  2003  arica_parinacota                            0.0                 0.0
338  2003       antofagasta                            0.0                17.8
339  2003             maule                            0.0                14.3
340  2003           atacama                            0.0                15.4
341  2003      la_araucania                            0.0                14.4
342  2003          ohiggins                            0.0                14.4
343  2003         los_lagos                            0.0                15.5
344  2003            biobio                            0.0                14.1
345  2003             aysen                            0.0                15.9
346  2003             nuble                            0.0                 0.0
347  2003          coquimbo                            0.0                15.7
348  2003          los_rios                            0.0                 0.0
349  2003     metropolitana                            0.0                14.9
350  2003        valparaiso                            0.0                13.9
351  2003        magallanes                            0.0                13.6
320  2004          tarapaca                            0.0                17.7
321  2004  arica_parinacota                            0.0                17.1
322  2004       antofagasta                            0.0                17.0
323  2004             maule                            0.0                14.5
324  2004           atacama                            0.0                16.5
325  2004      la_araucania                            0.0                15.0
326  2004          ohiggins                            0.0                14.9
327  2004         los_lagos                            0.0                16.1
328  2004            biobio                            0.0                14.5
329  2004             aysen                            0.0                17.0
330  2004             nuble                            0.0                 0.0
331  2004          coquimbo                            0.0                14.8
332  2004          los_rios                            0.0                14.6
333  2004     metropolitana                            0.0                15.2
334  2004        valparaiso                            0.0                14.1
335  2004        magallanes                            0.0                14.1
304  2005          tarapaca                            0.0                18.0
305  2005  arica_parinacota                            0.0                17.2
306  2005       antofagasta                            0.0                16.6
307  2005             maule                            0.0                14.5
308  2005           atacama                            0.0                16.7
309  2005      la_araucania                            0.0                14.6
310  2005          ohiggins                            0.0                14.8
311  2005         los_lagos                            0.0                16.1
312  2005            biobio                            0.0                14.3
313  2005             aysen                            0.0                16.7
314  2005             nuble                            0.0                 0.0
315  2005          coquimbo                            0.0                15.0
316  2005          los_rios                            0.0                14.4
317  2005     metropolitana                            0.0                14.9
318  2005        valparaiso                            0.0                14.1
319  2005        magallanes                            0.0                14.6
288  2006          tarapaca                            0.0                16.7
289  2006  arica_parinacota                            0.0                16.6
290  2006       antofagasta                            0.0                16.5
291  2006             maule                            0.0                13.4
292  2006           atacama                            0.0                17.1
293  2006      la_araucania                            0.0                14.0
294  2006          ohiggins                            0.0                13.6
295  2006         los_lagos                            0.0                14.9
296  2006            biobio                            0.0                13.7
297  2006             aysen                            0.0                16.1
298  2006             nuble                            0.0                 0.0
299  2006          coquimbo                            0.0                13.9
300  2006          los_rios                            0.0                13.8
301  2006     metropolitana                            0.0                14.3
302  2006        valparaiso                            0.0                13.0
303  2006        magallanes                            0.0                14.0
272  2007          tarapaca                            0.0                17.1
273  2007  arica_parinacota                            0.0                16.8
274  2007       antofagasta                            0.0                17.1
275  2007             maule                            0.0                13.9
276  2007           atacama                            0.0                17.3
277  2007      la_araucania                            0.0                14.3
278  2007          ohiggins                            0.0                14.3
279  2007         los_lagos                            0.0                15.4
280  2007            biobio                            0.0                14.0
281  2007             aysen                            0.0                16.5
282  2007             nuble                            0.0                 0.0
283  2007          coquimbo                            0.0                14.4
284  2007          los_rios                            0.0                13.9
285  2007     metropolitana                            0.0                14.7
286  2007        valparaiso                            0.0                13.4
287  2007        magallanes                            0.0                14.0
256  2008          tarapaca                            0.0                17.8
257  2008  arica_parinacota                            0.0                18.3
258  2008       antofagasta                            0.0                17.4
259  2008             maule                            0.0                14.2
260  2008           atacama                            0.0                17.5
261  2008      la_araucania                            0.0                14.3
262  2008          ohiggins                            0.0                14.7
263  2008         los_lagos                            0.0                15.7
264  2008            biobio                            0.0                13.9
265  2008             aysen                            0.0                17.2
266  2008             nuble                            0.0                 0.0
267  2008          coquimbo                            0.0                15.1

In [ ]:
ranking_madres_extranjeras = df_limpia.sort_values(by=["ano", "porcentajes_madres_extranjeras"], ascending=[False, False])
display(ranking_madres_extranjeras[["ano", "region", "porcentajes_madres_extranjeras", "tasa_natalidad_1000"]])

      ano            region porcentajes_madres_extranjeras tasa_natalidad_1000
32   2022          tarapaca                           47.9                12.7
34   2022       antofagasta                           40.6                10.6
33   2022  arica_parinacota                           38.1                11.3
45   2022     metropolitana                           26.3                 9.2
36   2022           atacama                           20.1                10.3
38   2022          ohiggins                           14.4                10.0
47   2022        magallanes                           13.4                 8.5
43   2022          coquimbo                           12.8                 9.4
46   2022        valparaiso                           12.6                 9.0
35   2022             maule                           10.3                10.3
39   2022         los_lagos                            7.9                 9.9
41   2022             aysen                            6.5                 9.5
40   2022            biobio                            5.9                 9.6
42   2022             nuble                            5.7                 9.4
37   2022      la_araucania                            3.9                10.2
44   2022          los_rios                            3.0                 9.3
48   2021          tarapaca                           44.9                11.3
50   2021       antofagasta                           37.4                 9.6
49   2021  arica_parinacota                           35.1                10.0
61   2021     metropolitana                           24.5                 8.9
52   2021           atacama                           16.3                 9.2
63   2021        magallanes                           13.6                 8.3
54   2021          ohiggins                           11.4                 9.3
62   2021        valparaiso                           11.1                 8.5
59   2021          coquimbo                           10.8                 8.9
51   2021             maule                            8.9                 9.4
55   2021         los_lagos                            7.3                 9.3
57   2021             aysen                            5.7                 9.1
56   2021            biobio                            5.6                 8.8
58   2021             nuble                            5.0                 8.7
60   2021          los_rios                            3.6                 8.4
53   2021      la_araucania                            3.4                 9.7
64   2020          tarapaca                           39.2                12.3
66   2020       antofagasta                           33.5                10.8
65   2020  arica_parinacota                           31.7                11.5
77   2020     metropolitana                           23.3                10.0
68   2020           atacama                           14.0                10.3
79   2020        magallanes                           12.5                 9.2
70   2020          ohiggins                           11.3                10.4
78   2020        valparaiso                           10.8                 9.4
75   2020          coquimbo                            9.5                 9.7
67   2020             maule                            8.7                10.3
71   2020         los_lagos                            7.0                10.1
73   2020             aysen                            5.5                 9.9
74   2020             nuble                            5.2                 9.6
72   2020            biobio                            5.1                 9.6
76   2020          los_rios                            4.8                 9.6
69   2020      la_araucania                            3.8                10.3
80   2019          tarapaca                           36.9                13.2
82   2019       antofagasta                           31.1                11.7
81   2019  arica_parinacota                           29.7                11.7
93   2019     metropolitana                           22.9                11.4
84   2019           atacama                           13.3                11.0
94   2019        valparaiso                           11.8                10.1
86   2019          ohiggins                           11.4                11.0
95   2019        magallanes                           10.0                 9.9
83   2019             maule                            9.6                11.2
91   2019          coquimbo                            9.6                10.6
87   2019         los_lagos                            5.9                10.8
90   2019             nuble                            4.6                10.0
89   2019             aysen                            4.5                10.5
88   2019            biobio                            4.4                10.4
92   2019          los_rios                            4.2                 9.9
85   2019      la_araucania                            3.7                11.2
96   2018          tarapaca                           33.7                14.0
98   2018       antofagasta                           28.5                12.5
97   2018  arica_parinacota                           22.8                12.2
109  2018     metropolitana                           21.0                12.5
100  2018           atacama                           10.0                12.2
110  2018        valparaiso                            9.7                11.0
102  2018          ohiggins                            9.4                11.6
111  2018        magallanes                            8.1                10.2
99   2018             maule                            7.9                11.8
107  2018          coquimbo                            7.6                11.3
106  2018             nuble                            4.6                10.6
103  2018         los_lagos                            4.1                11.3
105  2018             aysen                            4.1                11.9
108  2018          los_rios                            3.3                10.3
101  2018      la_araucania                            3.2                11.8
104  2018            biobio                            2.7                10.7
112  2017          tarapaca                           31.7                14.9
114  2017       antofagasta                           24.8                13.5
113  2017  arica_parinacota                           21.1                12.8
125  2017     metropolitana                           14.4                12.4
116  2017           atacama                            7.0                12.9
127  2017        magallanes                            5.0                11.0
123  2017          coquimbo                            4.0                11.6
126  2017        valparaiso                            3.0                10.8
118  2017          ohiggins                            2.9                11.4
121  2017             aysen                            2.5                11.5
115  2017             maule                            2.0                11.6
119  2017         los_lagos                            1.5                11.6
120  2017            biobio                            1.5                11.1
122  2017             nuble                            1.5                10.7
117  2017      la_araucania                            1.4                12.1
124  2017          los_rios                            1.1                10.7
128  2016          tarapaca                           27.5                15.9
130  2016       antofagasta                           22.5                14.7
133  2016      la_araucania                           20.0                12.6
129  2016  arica_parinacota                           16.9                13.2
141  2016     metropolitana                            9.7                13.1
132  2016           atacama                            6.1                13.4
143  2016        magallanes                            3.9                11.3
139  2016          coquimbo                            2.4                13.0
142  2016        valparaiso                            2.2                12.1
134  2016          ohiggins                            1.5                12.4
137  2016             aysen                            1.5                13.0
140  2016          los_rios                            1.0                11.2
131  2016             maule                            0.9                12.6
135  2016         los_lagos                            0.9                12.8
136  2016            biobio                            0.8                11.8
138  2016             nuble                            0.8                11.2
144  2015          tarapaca                           18.6                17.1
146  2015       antofagasta                           16.9                15.9
145  2015  arica_parinacota                           13.2                14.3
157  2015     metropolitana                            6.5                13.9
148  2015           atacama                            4.9                14.3
159  2015        magallanes                            2.9                12.4
155  2015          coquimbo                            1.8                13.0
153  2015             aysen                            1.6                13.1
158  2015        valparaiso                            1.5                13.0
151  2015         los_lagos                            1.0                13.3
147  2015             maule                            0.8                13.5
156  2015          los_rios                            0.7                11.6
149  2015      la_araucania                            0.6                13.5
152  2015            biobio                            0.6                12.7
154  2015             nuble                            0.6                11.9
150  2015          ohiggins                            0.1                13.2
160  2014          tarapaca                            0.0                17.8
161  2014  arica_parinacota                            0.0                15.1
162  2014       antofagasta                            0.0                16.7
163  2014             maule                            0.0                13.9
164  2014           atacama                            0.0                16.4
165  2014      la_araucania                            0.0                13.7
166  2014          ohiggins                            0.0                13.7
167  2014         los_lagos                            0.0                13.7
168  2014            biobio                            0.0                13.2
169  2014             aysen                            0.0                14.4
170  2014             nuble                            0.0                11.9
171  2014          coquimbo                            0.0                15.3
172  2014          los_rios                            0.0                12.6
173  2014     metropolitana                            0.0                14.3
174  2014        valparaiso                            0.0                13.4
175  2014        magallanes                            0.0                12.9
176  2013          tarapaca                            0.0                18.1
177  2013  arica_parinacota                            0.0                15.2
178  2013       antofagasta                            0.0                16.4
179  2013             maule                            0.0                13.4
180  2013           atacama                            0.0                16.0
181  2013      la_araucania                            0.0                13.2
182  2013          ohiggins                            0.0                13.5
183  2013         los_lagos                            0.0                13.6
184  2013            biobio                            0.0                12.7
185  2013             aysen                            0.0                13.6
186  2013             nuble                            0.0                11.7
187  2013          coquimbo                            0.0                15.2
188  2013          los_rios                            0.0                12.2
189  2013     metropolitana                            0.0                13.9
190  2013        valparaiso                            0.0                13.0
191  2013        magallanes                            0.0                12.6
192  2012          tarapaca                            0.0                18.4
193  2012  arica_parinacota                            0.0                15.7
194  2012       antofagasta                            0.0                16.6
195  2012             maule                            0.0                13.2
196  2012           atacama                            0.0                16.2
197  2012      la_araucania                            0.0                13.4
198  2012          ohiggins                            0.0                13.6
199  2012         los_lagos                            0.0                13.7
200  2012            biobio                            0.0                12.9
201  2012             aysen                            0.0                14.7
202  2012             nuble                            0.0                12.0
203  2012          coquimbo                            0.0                15.3
204  2012          los_rios                            0.0                12.9
205  2012     metropolitana                            0.0                14.1
206  2012        valparaiso                            0.0                13.3
207  2012        magallanes                            0.0                13.0
208  2011          tarapaca                            0.0                18.1
209  2011  arica_parinacota                            0.0                20.0
210  2011       antofagasta                            0.0                17.2
211  2011             maule                            0.0                13.5
212  2011           atacama                            0.0                18.2
213  2011      la_araucania                            0.0                13.8
214  2011          ohiggins                            0.0                13.8
215  2011         los_lagos                            0.0                14.2
216  2011            biobio                            0.0                13.7
217  2011             aysen                            0.0                14.6
218  2011             nuble                            0.0                 0.0
219  2011          coquimbo                            0.0                15.4
220  2011          los_rios                            0.0                13.7
221  2011     metropolitana                            0.0                14.5
222  2011        valparaiso                            0.0                13.3
223  2011        magallanes                            0.0                13.4
224  2010          tarapaca                            0.0                18.0
225  2010  arica_parinacota                            0.0                20.0
226  2010       antofagasta                            0.0                17.5
227  2010             maule                            0.0                14.0
228  2010           atacama                            0.0                18.1
229  2010      la_araucania                            0.0                13.8
230  2010          ohiggins                            0.0                14.4
231  2010         los_lagos                            0.0                14.9
232  2010            biobio                            0.0                13.9
233  2010             aysen                            0.0                15.7
234  2010             nuble                            0.0                 0.0
235  2010          coquimbo                            0.0                15.6
236  2010          los_rios                            0.0                14.4
237  2010     metropolitana                            0.0                14.7
238  2010        valparaiso                            0.0                13.5
239  2010        magallanes                            0.0                14.2
240  2009          tarapaca                            0.0                18.7
241  2009  arica_parinacota                            0.0                19.1
242  2009       antofagasta                            0.0                17.7
243  2009             maule                            0.0                14.2
244  2009           atacama                            0.0                18.8
245  2009      la_araucania                            0.0                14.2
246  2009          ohiggins                            0.0                14.6
247  2009         los_lagos                            0.0                15.9
248  2009            biobio                            0.0                14.1
249  2009             aysen                            0.0                16.4
250  2009             nuble                            0.0                 0.0
251  2009          coquimbo                            0.0                15.3
252  2009          los_rios                            0.0                14.2
253  2009     metropolitana                            0.0                15.1
254  2009        valparaiso                            0.0                13.7
255  2009        magallanes                            0.0                14.1
256  2008          tarapaca                            0.0                17.8
257  2008  arica_parinacota                            0.0                18.3
258  2008       antofagasta                            0.0                17.4
259  2008             maule                            0.0                14.2
260  2008           atacama                            0.0                17.5
261  2008      la_araucania                            0.0                14.3
262  2008          ohiggins                            0.0                14.7
263  2008         los_lagos                            0.0                15.7
264  2008            biobio                            0.0                13.9
265  2008             aysen                            0.0                17.2
266  2008             nuble                            0.0                 0.0
267  2008          coquimbo                            0.0                15.1
268  2008          los_rios                            0.0                14.2
269  2008     metropolitana                            0.0                14.9
270  2008        valparaiso                            0.0                13.5
271  2008        magallanes                            0.0                14.5
272  2007          tarapaca                            0.0                17.1
273  2007  arica_parinacota                            0.0                16.8
274  2007       antofagasta                            0.0                17.1
275  2007             maule                            0.0                13.9
276  2007           atacama                            0.0                17.3
277  2007      la_araucania                            0.0                14.3
278  2007          ohiggins                            0.0                14.3
279  2007         los_lagos                            0.0                15.4
280  2007            biobio                            0.0                14.0
281  2007             aysen                            0.0                16.5
282  2007             nuble                            0.0                 0.0
283  2007          coquimbo                            0.0                14.4

In [ ]:
top_5_madres_extranjeras = df_limpia.groupby("region")["porcentajes_madres_extranjeras"].mean().reset_index()
top_5_madres_extranjeras = top_5_madres_extranjeras.sort_values(by="porcentajes_madres_extranjeras", ascending=False).head(5)
display(top_5_madres_extranjeras)

              region porcentajes_madres_extranjeras
14          tarapaca                       9.346667
0        antofagasta                       7.843333
1   arica_parinacota                       6.953333
11     metropolitana                       4.953333
2            atacama                       3.056667

In [ ]:
top_5_madres_extranjeras = df_limpia.groupby("region")["porcentajes_madres_extranjeras"].mean().reset_index()
top_5_madres_extranjeras = top_5_madres_extranjeras.sort_values(by="porcentajes_madres_extranjeras", ascending=False).head(5)
display(top_5_madres_extranjeras)

grafico_barras_top5 = alt.Chart(top_5_madres_extranjeras).mark_bar().encode(
    x='porcentajes_madres_extranjeras',
    y=alt.Y('region', sort='-x')
).properties(height=300)

              region porcentajes_madres_extranjeras
14          tarapaca                       9.346667
0        antofagasta                       7.843333
1   arica_parinacota                       6.953333
11     metropolitana                       4.953333
2            atacama                       3.056667

In [ ]:
top_5_ano_region_madres_extranjeras = df_limpia.sort_values(by="porcentajes_madres_extranjeras", ascending=False).head(5)
display(top_5_ano_region_madres_extranjeras[["ano", "region", "porcentajes_madres_extranjeras", "tasa_natalidad_1000", "nacidos_vivos"]])

,ano,region,porcentajes_madres_extranjeras,tasa_natalidad_1000,nacidos_vivos
32,2022,tarapaca,47.9,12.7,5.023
48,2021,tarapaca,44.9,11.3,4.396
34,2022,antofagasta,40.6,10.6,7.484
64,2020,tarapaca,39.2,12.3,4.709
33,2022,arica_parinacota,38.1,11.3,2.916

In [ ]:
df_limpia[["tasa_natalidad_1000", "porcentajes_madres_extranjeras"]].corr()

,tasa_natalidad_1000,porcentajes_madres_extranjeras
tasa_natalidad_1000,1.000000,-0.157947
porcentajes_madres_extranjeras,-0.157947,1.000000

In [ ]:
primer_ano = df_limpia['ano'].min()
ultimo_ano = df_limpia['ano'].max()
df_inicio = df_limpia[df_limpia["ano"] == primer_ano][["region", "tasa_natalidad_1000"]].rename(columns={"tasa_natalidad_1000": "tasa_inicio"})
df_final = df_limpia[df_limpia["ano"] == ultimo_ano][["region", "tasa_natalidad_1000"]].rename(columns={"tasa_natalidad_1000": "tasa_final"})
cambio_tasa = df_inicio.merge(df_final, on="region")
cambio_tasa["cambios_tasa"] = cambio_tasa["tasa_final"] - cambio_tasa["tasa_inicio"]
cambio_tasa_regional = cambio_tasa.sort_values(by="cambios_tasa", ascending=False)
display(cambio_tasa_regional)

              region tasa_inicio tasa_final cambios_tasa
1   arica_parinacota         0.0       11.3         11.3
10             nuble         0.0        9.4          9.4
12          los_rios         0.0        9.3          9.3
0           tarapaca        21.7       12.7         -9.0
5       la_araucania        19.2       10.2         -9.0
15        magallanes        17.8        8.5         -9.3
7          los_lagos        19.5        9.9         -9.6
6           ohiggins        19.7       10.0         -9.7
8             biobio        19.3        9.6         -9.7
3              maule        20.1       10.3         -9.8
14        valparaiso        19.0        9.0        -10.0
9              aysen        19.7        9.5        -10.2
13     metropolitana        20.3        9.2        -11.1
4            atacama        22.4       10.3        -12.1
2        antofagasta        22.8       10.6        -12.2
11          coquimbo        21.7        9.4        -12.3

In [ ]:
df_inicio_madres = df_limpia[df_limpia["ano"] == primer_ano][["region", "porcentajes_madres_extranjeras"]].rename(columns={"porcentajes_madres_extranjeras": "porcentajes_madres_extranjeras_inicio"})
df_final_madres = df_limpia[df_limpia["ano"] == ultimo_ano][["region", "porcentajes_madres_extranjeras"]].rename(columns={"porcentajes_madres_extranjeras": "porcentajes_madres_extranjeras_final"})
cambio_madres_region = df_inicio_madres.merge(df_final_madres, on="region")
cambio_madres_region["cambio_madres_extranjeras"] = cambio_madres_region["porcentajes_madres_extranjeras_final"] - cambio_madres_region["porcentajes_madres_extranjeras_inicio"]
cambio_madres_region = cambio_madres_region.sort_values(by="cambio_madres_extranjeras", ascending=False)
display(cambio_madres_region)

,region,porcentajes_madres_extranjeras_inicio,porcentajes_madres_extranjeras_final,cambio_madres_extranjeras
0,tarapaca,0.0,47.9,47.9
2,antofagasta,0.0,40.6,40.6
1,arica_parinacota,0.0,38.1,38.1
13,metropolitana,0.0,26.3,26.3
4,atacama,0.0,20.1,20.1
6,ohiggins,0.0,14.4,14.4
15,magallanes,0.0,13.4,13.4
11,coquimbo,0.0,12.8,12.8
14,valparaiso,0.0,12.6,12.6
3,maule,0.0,10.3,10.3
7,los_lagos,0.0,7.9,7.9
9,aysen,0.0,6.5,6.5
8,biobio,0.0,5.9,5.9
10,nuble,0.0,5.7,5.7
5,la_araucania,0.0,3.9,3.9
12,los_rios,0.0,3.0,3.0

In [ ]:
resumen_regiones = cambio_tasa_regional.merge(cambio_madres_region, on="region")
display(resumen_regiones[["region", "tasa_inicio", "tasa_final", "cambios_tasa", "porcentajes_madres_extranjeras_inicio", "porcentajes_madres_extranjeras_final", "cambio_madres_extranjeras"]].sort_values(by="cambio_madres_extranjeras", ascending=False))

,region,tasa_inicio,tasa_final,cambios_tasa,porcentajes_madres_extranjeras_inicio,porcentajes_madres_extranjeras_final,cambio_madres_extranjeras
3,tarapaca,21.7,12.7,-9.0,0.0,47.9,47.9
14,antofagasta,22.8,10.6,-12.2,0.0,40.6,40.6
0,arica_parinacota,0.0,11.3,11.3,0.0,38.1,38.1
12,metropolitana,20.3,9.2,-11.1,0.0,26.3,26.3
13,atacama,22.4,10.3,-12.1,0.0,20.1,20.1
7,ohiggins,19.7,10.0,-9.7,0.0,14.4,14.4
5,magallanes,17.8,8.5,-9.3,0.0,13.4,13.4
15,coquimbo,21.7,9.4,-12.3,0.0,12.8,12.8
10,valparaiso,19.0,9.0,-10.0,0.0,12.6,12.6
9,maule,20.1,10.3,-9.8,0.0,10.3,10.3
6,los_lagos,19.5,9.9,-9.6,0.0,7.9,7.9
11,aysen,19.7,9.5,-10.2,0.0,6.5,6.5
8,biobio,19.3,9.6,-9.7,0.0,5.9,5.9
1,nuble,0.0,9.4,9.4,0.0,5.7,5.7
4,la_araucania,19.2,10.2,-9.0,0.0,3.9,3.9
2,los_rios,0.0,9.3,9.3,0.0,3.0,3.0

In [ ]:
import altair as alt
resumen_regiones = cambio_tasa_regional.merge(cambio_madres_region, on="region")
display(resumen_regiones[["region", "tasa_inicio", "tasa_final", "cambios_tasa", "porcentajes_madres_extranjeras_inicio", "porcentajes_madres_extranjeras_final", "cambio_madres_extranjeras"]].sort_values(by="cambio_madres_extranjeras", ascending=False))

grafico_barras = alt.Chart(resumen_regiones).mark_bar().encode(
    x='cambio_madres_extranjeras',
    y='region'
)

,region,tasa_inicio,tasa_final,cambios_tasa,porcentajes_madres_extranjeras_inicio,porcentajes_madres_extranjeras_final,cambio_madres_extranjeras
3,tarapaca,21.7,12.7,-9.0,0.0,47.9,47.9
14,antofagasta,22.8,10.6,-12.2,0.0,40.6,40.6
0,arica_parinacota,0.0,11.3,11.3,0.0,38.1,38.1
12,metropolitana,20.3,9.2,-11.1,0.0,26.3,26.3
13,atacama,22.4,10.3,-12.1,0.0,20.1,20.1
7,ohiggins,19.7,10.0,-9.7,0.0,14.4,14.4
5,magallanes,17.8,8.5,-9.3,0.0,13.4,13.4
15,coquimbo,21.7,9.4,-12.3,0.0,12.8,12.8
10,valparaiso,19.0,9.0,-10.0,0.0,12.6,12.6
9,maule,20.1,10.3,-9.8,0.0,10.3,10.3
6,los_lagos,19.5,9.9,-9.6,0.0,7.9,7.9
11,aysen,19.7,9.5,-10.2,0.0,6.5,6.5
8,biobio,19.3,9.6,-9.7,0.0,5.9,5.9
1,nuble,0.0,9.4,9.4,0.0,5.7,5.7
4,la_araucania,19.2,10.2,-9.0,0.0,3.9,3.9
2,los_rios,0.0,9.3,9.3,0.0,3.0,3.0

In [ ]:
import pandas as pd
import altair as alt

df_lineas = df_limpia.copy()

df_lineas["ano"] = pd.to_numeric(df_lineas["ano"], errors="coerce")

df_lineas["tasa_natalidad_1000"] = (
    df_lineas["tasa_natalidad_1000"]
        .astype(str)
        .str.replace(",", ".", regex=False)
    )

df_lineas["tasa_natalidad_1000"] = pd.to_numeric(
    df_lineas["tasa_natalidad_1000"],
    errors="coerce"
)

df_lineas = df_lineas.dropna(subset=["ano", "region", "tasa_natalidad_1000"])
df_lineas = df_lineas.sort_values(["region","ano"])
display(df_lineas)

,ano,region,nacidos_vivos,tasa_natalidad_1000,porcentajes_madres_extranjeras
498,1993,antofagasta,9.643,22.8,0.0
482,1994,antofagasta,9.562,22.2,0.0
466,1995,antofagasta,9.389,21.5,0.0
450,1996,antofagasta,9.763,22.0,0.0
434,1997,antofagasta,9.516,21.2,0.0
418,1998,antofagasta,9.568,21.0,0.0
402,1999,antofagasta,9.199,19.9,0.0
386,2000,antofagasta,9.064,19.4,0.0
370,2001,antofagasta,8.709,18.4,0.0
354,2002,antofagasta,8.842,18.4,0.0
338,2003,antofagasta,8.663,17.8,0.0
322,2004,antofagasta,9.052,17.0,0.0
306,2005,antofagasta,9.000,16.6,0.0
290,2006,antofagasta,8.975,16.5,0.0
274,2007,antofagasta,9.419,17.1,0.0
258,2008,antofagasta,9.706,17.4,0.0
242,2009,antofagasta,9.988,17.7,0.0
226,2010,antofagasta,10.016,17.5,0.0
210,2011,antofagasta,9.932,17.2,0.0
194,2012,antofagasta,9.817,16.6,0.0
178,2013,antofagasta,9.841,16.4,0.0
162,2014,antofagasta,10.191,16.7,0.0
146,2015,antofagasta,9.885,15.9,16.9
130,2016,antofagasta,9.214,14.7,22.5
114,2017,antofagasta,8.396,13.5,24.8
98,2018,antofagasta,8.049,12.5,28.5
82,2019,antofagasta,7.770,11.7,31.1
66,2020,antofagasta,7.434,10.8,33.5
50,2021,antofagasta,6.748,9.6,37.4
34,2022,antofagasta,7.484,10.6,40.6
497,1993,arica_parinacota,0.000,0.0,0.0
481,1994,arica_parinacota,0.000,0.0,0.0
465,1995,arica_parinacota,0.000,0.0,0.0
449,1996,arica_parinacota,0.000,0.0,0.0
433,1997,arica_parinacota,0.000,0.0,0.0
417,1998,arica_parinacota,0.000,0.0,0.0
401,1999,arica_parinacota,0.000,0.0,0.0
385,2000,arica_parinacota,0.000,0.0,0.0
369,2001,arica_parinacota,0.000,0.0,0.0
353,2002,arica_parinacota,0.000,0.0,0.0
337,2003,arica_parinacota,0.000,0.0,0.0
321,2004,arica_parinacota,3.270,17.1,0.0
305,2005,arica_parinacota,3.287,17.2,0.0
289,2006,arica_parinacota,3.099,16.6,0.0
273,2007,arica_parinacota,3.158,16.8,0.0
257,2008,arica_parinacota,3.364,18.3,0.0
241,2009,arica_parinacota,3.559,19.1,0.0
225,2010,arica_parinacota,3.646,20.0,0.0
209,2011,arica_parinacota,3.640,20.0,0.0
193,2012,arica_parinacota,3.558,15.7,0.0
177,2013,arica_parinacota,3.504,15.2,0.0
161,2014,arica_parinacota,3.546,15.1,0.0
145,2015,arica_parinacota,3.414,14.3,13.2
129,2016,arica_parinacota,3.169,13.2,16.9
113,2017,arica_parinacota,3.037,12.8,21.1
97,2018,arica_parinacota,2.958,12.2,22.8
81,2019,arica_parinacota,2.893,11.7,29.7
65,2020,arica_parinacota,2.886,11.5,31.7
49,2021,arica_parinacota,2.553,10.0,35.1
33,2022,arica_parinacota,2.916,11.3,38.1
500,1993,atacama,3.377,22.4,0.0
484,1994,atacama,5.165,21.1,0.0
468,1995,atacama,5.161,20.6,0.0
452,1996,atacama,5.071,19.9,0.0
436,1997,atacama,4.698,18.1,0.0
420,1998,atacama,4.621,17.5,0.0
404,1999,atacama,4.641,17.2,0.0
388,2000,atacama,4.443,16.2,0.0
372,2001,atacama,4.603,16.6,0.0
356,2002,atacama,4.310,15.3,0.0
340,2003,atacama,4.407,15.4,0.0
324,2004,atacama,4.434,16.5,0.0
308,2005,atacama,4.523,16.7,0.0
292,2006,atacama,4.648,17.1,0.0
276,2007,atacama,4.720,17.3,0.0
260,2008,atacama,4.803,17.5,0.0
244,2009,atacama,5.194,18.8,0.0
228,2010,atacama,5.069,18.1,0.0
212,2011,atacama,5.116,18.2,0.0
196,2012,atacama,4.855,16.2,0.0
180,2013,atacama,4.849,16.0,0.0
164,2014,atacama,5.014,16.4,0.0
148,2015,atacama,4.466,14.3,4.9
132,2016,atacama,4.230,13.4,6.1
116,2017,atacama,3.929,12.9,7.0
100,2018,atacama,3.730,12.2,10.0
84,2019,atacama,3.425,11.0,13.3
68,2020,atacama,3.247,10.3,14.0
52,2021,atacama,2.920,9.2,16.3
36,2022,atacama,3.265,10.3,20.1
505,1993,aysen,1.661,19.7,0.0
489,1994,aysen,1.688,19.6,0.0
473,1995,aysen,1.543,17.6,0.0
457,1996,aysen,1.585,17.7,0.0
441,1997,aysen,1.536,16.9,0.0
425,1998,aysen,1.566,17.0,0.0
409,1999,aysen,1.530,16.3,0.0
393,2000,aysen,1.498,15.8,0.0
377,2001,aysen,1.595,16.5,0.0
361,2002,aysen,1.579,16.2,0.0
345,2003,aysen,1.578,15.9,0.0
329,2004,aysen,1.674,17.0,0.0
313,2005,aysen,1.662,16.7,0.0
297,2006,aysen,1.563,16.1,0.0
281,2007,aysen,1.679,16.5,0.0
265,2008,aysen,1.733,17.2,0.0
249,2009,aysen,1.687,16.4,0.0
233,2010,aysen,1.636,15.7,0.0
217,2011,aysen,1.545,14.6,0.0
201,2012,aysen,1.540,14.7,0.0
185,2013,aysen,1.440,13.6,0.0
169,2014,aysen,1.535,14.4,0.0
153,2015,aysen,1.413,13.1,1.6
137,2016,aysen,1.408,13.0,1.5
121,2017,aysen,1.215,11.5,2.5
105,2018,aysen,1.258,11.9,4.1
89,2019,aysen,1.120,10.5,4.5
73,2020,aysen,1.059,9.9,5.5
57,2021,aysen,982.000,9.1,5.7
41,2022,aysen,1.023,9.5,6.5
504,1993,biobio,34.470,19.3,0.0
488,1994,biobio,33.573,18.6,0.0
472,1995,biobio,32.251,17.6,0.0
456,1996,biobio,32.063,17.3,0.0
440,1997,biobio,31.639,16.9,0.0
424,1998,biobio,30.635,16.2,0.0
408,1999,biobio,29.722,15.5,0.0
392,2000,biobio,28.908,14.9,0.0
376,2001,biobio,28.972,14.8,0.0
360,2002,biobio,27.990,14.2,0.0
344,2003,biobio,28.040,14.1,0.0
328,2004,biobio,28.268,14.5,0.0
312,2005,biobio,28.170,14.3,0.0
296,2006,biobio,27.028,13.7,0.0
280,2007,biobio,27.682,14.0,0.0
264,2008,biobio,27.779,13.9,0.0
248,2009,biobio,28.313,14.1,0.0
232,2010,biobio,22.293,13.9,0.0
216,2011,biobio,21.986,13.7,0.0
200,2012,biobio,20.997,12.9,0.0
184,2013,biobio,20.714,12.7,0.0
168,2014,biobio,21.599,13.2,0.0
152,2015,biobio,21.023,12.7,0.6
136,2016,biobio,19.582,11.8,0.8
120,2017,biobio,18.175,11.1,1.5
104,2018,biobio,17.652,10.7,2.7
88,2019,biobio,17.107,10.4,4.4
72,2020,biobio,16.006,9.6,5.1
56,2021,biobio,14.639,8.8,5.6
40,2022,biobio,16.115,9.6,5.9
507,1993,coquimbo,11.243,21.7,0.0
491,1994,coquimbo,11.038,20.9,0.0
475,1995,coquimbo,10.619,19.8,0.0
459,1996,coquimbo,10.606,19.5,0.0
443,1997,coquimbo,10.217,18.5,0.0
427,1998,coquimbo,9.875,17.6,0.0
411,1999,coquimbo,9.939,17.4,0.0
395,2000,coquimbo,10.221,17.7,0.0
379,2001,coquimbo,10.199,17.4,0.0
363,2002,coquimbo,9.608,16.2,0.0
347,2003,coquimbo,9.459,15.7,0.0
331,2004,coquimbo,9.691,14.8,0.0
315,2005,coquimbo,9.992,15.0,0.0
299,2006,coquimbo,9.372,13.9,0.0
283,2007,coquimbo,9.794,14.4,0.0
267,2008,coquimbo,10.447,15.1,0.0
251,2009,coquimbo,10.801,15.3,0.0
235,2010,coquimbo,11.225,15.6,0.0
219,2011,coquimbo,11.148,15.4,0.0
203,2012,coquimbo,11.217,15.3,0.0
187,2013,coquimbo,11.343,15.2,0.0
171,2014,coquimbo,11.577,15.3,0.0
155,2015,coquimbo,11.010,13.0,1.8
139,2016,coquimbo,10.126,13.0,2.4
123,2017,coquimbo,9.215,11.6,4.0
107,2018,coquimbo,9.095,11.3,7.6
91,2019,coquimbo,8.666,10.6,9.6
75,2020,coquimbo,8.127,9.7,9.5
59,2021,coquimbo,7.564,8.9,10.8
43,2022,coquimbo,8.019,9.4,12.8
501,1993,la_araucania,15.487,19.2,0.0
485,1994,la_araucania,15.236,18.7,0.0
469,1995,la_araucania,14.667,17.8,0.0
453,1996,la_araucania,14.882,17.4,0.0
437,1997,la_araucania,14.589,17.2,0.0
421,1998,la_araucania,14.245,16.6,0.0
405,1999,la_araucania,13.858,16.0,0.0
389,2000,la_araucania,13.580,15.5,0.0
373,2001,la_araucania,13.657,15.5,0.0
357,2002,la_araucania,13.456,15.1,0.0
341,2003,la_araucania,13.013,14.4,0.0
325,2004,la_araucania,13.819,15.0,0.0
309,2005,la_araucania,13.545,14.6,0.0
293,2006,la_araucania,13.016,14.0,0.0
277,2007,la_araucania,13.418,14.3,0.0
261,2008,la_araucania,13.494,14.3,0.0
245,2009,la_araucania,13.546,14.2,0.0
229,2010,la_araucania,13.367,13.8,0.0
213,2011,la_araucania,13.295,13.8,0.0
197,2012,la_araucania,13.024,13.4,0.0
181,2013,la_araucania,12.877,13.2,0.0
165,2014,la_araucania,13.313,13.7,0.0
149,2015,la_araucania,13.324,13.5,0.6
133,2016,la_araucania,12.534,12.6,20.0
117,2017,la_araucania,12.005,12.1,1.4
101,2018,la_araucania,11.772,11.8,3.2
85,2019,la_araucania,11.302,11.2,3.7
69,2020,la_araucania,10.441,10.3,3.8
53,2021,la_araucania,9.860,9.7,3.4
37,2022,la_araucania,10.405,10.2,3.9
503,1993,los_lagos,19.076,19.5,0.0
487,1994,los_lagos,19.015,19.2,0.0
471,1995,los_lagos,18.394,18.3,0.0
455,1996,los_lagos,18.472,18.2,0.0
439,1997,los_lagos,18.365,17.9,0.0
423,1998,los_lagos,7.783,17.1,0.0
407,1999,los_lagos,17.242,16.4,0.0
391,2000,los_lagos,17.457,16.4,0.0
375,2001,los_lagos,17.507,16.3,0.0
359,2002,los_lagos,17.506,16.2,0.0
343,2003,los_lagos,16.935,15.5,0.0
327,2004,los_lagos,12.442,16.1,0.0
311,2005,los_lagos,12.642,16.1,0.0
295,2006,los_lagos,11.758,14.9,0.0
279,2007,los_lagos,12.335,15.4,0.0
263,2008,los_lagos,12.772,15.7,0.0
247,2009,los_lagos,13.072,15.9,0.0
231,2010,los_lagos,12.413,14.9,0.0
215,2011,los_lagos,11.911,14.2,0.0
199,2012,los_lagos,11.287,13.7,0.0
183,2013,los_lagos,11.191,13.6,0.0
167,2014,los_lagos,11.380,13.7,0.0
151,2015,los_lagos,11.158,13.3,1.0
135,2016,los_lagos,10.787,12.8,0.9
119,2017,los_lagos,10.046,11.6,1.5
103,2018,los_lagos,9.921,11.3,4.1
87,2019,los_lagos,9.574,10.8,5.9
71,2020,los_lagos,8.958,10.1,7.0
55,2021,los_lagos,8.370,9.3,7.3
39,2022,los_lagos,8.955,9.9,7.9
508,1993,los_rios,0.000,0.0,0.0
492,1994,los_rios,0.000,0.0,0.0
476,1995,los_rios,0.000,0.0,0.0
460,1996,los_rios,0.000,0.0,0.0
444,1997,los_rios,0.000,0.0,0.0
428,1998,los_rios,0.000,0.0,0.0
412,1999,los_rios,0.000,0.0,0.0
396,2000,los_rios,0.000,0.0,0.0
380,2001,los_rios,0.000,0.0,0.0
364,2002,los_rios,0.000,0.0,0.0
348,2003,los_rios,0.000,0.0,0.0
332,2004,los_rios,5.410,14.6,0.0
316,2005,los_rios,5.355,14.4,0.0
300,2006,los_rios,5.155,13.8,0.0
284,2007,los_rios,5.154,13.9,0.0
268,2008,los_rios,5.306,14.2,0.0
252,2009,los_rios,5.349,14.2,0.0
236,2010,los_rios,5.433,14.4,0.0
220,2011,los_rios,5.176,13.7,0.0
204,2012,los_rios,5.124,12.9,0.0
188,2013,los_rios,4.814,12.2,0.0
172,2014,los_rios,5.063,12.6,0.0
156,2015,los_rios,4.664,11.6,0.7
140,2016,los_rios,4.532,11.2,1.0
124,2017,los_rios,4.268,10.7,1.1
108,2018,los_rios,4.106,10.3,3.3
92,2019,los_rios,4.004,9.9,4.2
76,2020,los_rios,3.898,9.6,4.8
60,2021,los_rios,3.435,8.4,3.6
44,2022,los_rios,3.780,9.3,3.0
511,1993,magallanes,2.633,17.8,0.0
495,1994,magallanes,2.515,16.8,0.0
479,1995,magallanes,2.495,16.5,0.0
463,1996,magallanes,2.548,16.7,0.0
447,1997,magallanes,2.466,16.0,0.0
431,1998,magallanes,2.488,16.0,0.0
415,1999,magallanes,2.413,15.4,0.0
399,2000,magallanes,2.352,14.9,0.0
383,2001,magallanes,2.232,14.0,0.0
367,2002,magallanes,2.243,14.0,0.0
351,2003,magallanes,2.198,13.6,0.0
335,2004,magallanes,2.195,14.1,0.0
319,2005,magallanes,2.271,14.6,0.0
303,2006,magallanes,2.127,14.0,0.0
287,2007,magallanes,2.173,14.0,0.0
271,2008,magallanes,2.264,14.5,0.0
255,2009,magallanes,2.217,14.1,0.0
239,2010,magallanes,2.243,14.2,0.0
223,2011,magallanes,2.118,13.4,0.0
207,2012,magallanes,2.108,13.0,0.0
191,2013,magallanes,2.041,12.6,0.0
175,2014,magallanes,2.104,12.9,0.0
159,2015,magallanes,2.032,12.4,2.9
143,2016,magallanes,1.873,11.3,3.9
127,2017,magallanes,1.883,11.0,5.0
111,2018,magallanes,1.757,10.2,8.1
95,2019,magallanes,1.743,9.9,10.0
79,2020,magallanes,1.638,9.2,12.5
63,2021,magallanes,1.494,8.3,13.6
47,2022,magallanes,1.539,8.5,13.4
499,1993,maule,17.146,20.1,0.0
483,1994,maule,16.783,19.5,0.0
467,1995,maule,15.812,18.1,0.0
451,1996,maule,15.489,17.6,0.0
435,1997,maule,14.962,16.8,0.0
419,1998,maule,14.812,16.5,0.0
403,1999,maule,14.437,15.9,0.0
387,2000,maule,14.237,15.6,0.0
371,2001,maule,13.967,15.1,0.0
355,2002,maule,13.730,14.8,0.0
339,2003,maule,13.453,14.3,0.0
323,2004,maule,13.892,14.5,0.0
307,2005,maule,14.008,14.5,0.0
291,2006,maule,13.099,13.4,0.0
275,2007,maule,13.566,13.9,0.0
259,2008,maule,14.045,14.2,0.0
243,2009,maule,14.108,14.2,0.0
227,2010,maule,14.103,14.0,0.0
211,2011,maule,13.640,13.5,0.0
195,2012,maule,13.429,13.2,0.0
179,2013,maule,13.714,13.4,0.0
163,2014,maule,14.345,13.9,0.0
147,2015,maule,14.068,13.5,0.8
131,2016,maule,13.225,12.6,0.9
115,2017,maule,12.632,11.6,2.0
99,2018,maule,13.070,11.8,7.9
83,2019,maule,12.496,11.2,9.6
67,2020,maule,11.667,10.3,8.7
51,2021,maule,10.689,9.4,8.9
35,2022,maule,11.837,10.3,10.3
509,1993,metropolitana,110.356,20.3,0.0
493,1994,metropolitana,110.774,20.0,0.0
477,1995,metropolitana,108.363,19.2,0.0
461,1996,metropolitana,107.586,18.8,0.0
445,1997,metropolitana,105.544,18.1,0.0
429,1998,metropolitana,105.471,17.8,0.0
413,1999,metropolitana,102.389,17.0,0.0
397,2000,metropolitana,102.205,16.7,0.0
381,2001,metropolitana,100.694,16.3,0.0
365,2002,metropolitana,96.996,15.5,0.0
349,2003,metropolitana,94.728,14.9,0.0
333,2004,metropolitana,97.982,15.2,0.0
317,2005,metropolitana,97.653,14.9,0.0
301,2006,metropolitana,93.593,14.3,0.0
285,2007,metropolitana,97.596,14.7,0.0
269,2008,metropolitana,99.873,14.9,0.0
253,2009,metropolitana,102.248,15.1,0.0
237,2010,metropolitana,101.047,14.7,0.0
221,2011,metropolitana,100.415,14.5,0.0
205,2012,metropolitana,99.488,14.1,0.0
189,2013,metropolitana,99.081,13.9,0.0
173,2014,metropolitana,103.059,14.3,0.0
157,2015,metropolitana,101.087,13.9,6.5
141,2016,metropolitana,96.616,13.1,9.7
125,2017,metropolitana,92.727,12.4,14.4
109,2018,metropolitana,95.834,12.5,21.0
93,2019,metropolitana,89.770,11.4,22.9
77,2020,metropolitana,81.351,10.0,23.3
61,2021,metropolitana,73.062,8.9,24.5
45,2022,metropolitana,76.129,9.2,26.3
506,1993,nuble,0.000,0.0,0.0
490,1994,nuble,0.000,0.0,0.0
474,1995,nuble,0.000,0.0,0.0
458,1996,nuble,0.000,0.0,0.0
442,1997,nuble,0.000,0.0,0.0
426,1998,nuble,0.000,0.0,0.0
410,1999,nuble,0.000,0.0,0.0
394,2000,nuble,0.000,0.0,0.0
378,2001,nuble,0.000,0.0,0.0
362,2002,nuble,0.000,0.0,0.0
346,2003,nuble,0.000,0.0,0.0
330,2004,nuble,0.000,0.0,0.0
314,2005,nuble,0.000,0.0,0.0
298,2006,nuble,0.000,0.0,0.0
282,2007,nuble,0.000,0.0,0.0
266,2008,nuble,0.000,0.0,0.0
250,2009,nuble,0.000,0.0,0.0
234,2010,nuble,0.000,0.0,0.0
218,2011,nuble,0.000,0.0,0.0
202,2012,nuble,5.732,12.0,0.0
186,2013,nuble,5.590,11.7,0.0
170,2014,nuble,5.899,11.9,0.0
154,2015,nuble,5.766,11.9,0.6
138,2016,nuble,5.453,11.2,0.8
122,2017,nuble,5.333,10.7,1.5
106,2018,nuble,5.324,10.6,4.6
90,2019,nuble,5.065,10.0,4.6
74,2020,nuble,4.885,9.6,5.2
58,2021,nuble,4.481,8.7,5.0
42,2022,nuble,4.838,9.4,5.7
502,1993,ohiggins,14.079,19.7,0.0
486,1994,ohiggins,13.753,18.9,0.0
470,1995,ohiggins,13.432,18.2,0.0
454,1996,ohiggins,13.189,17.6,0.0
438,1997,ohiggins,3.104,17.3,0.0
422,1998,ohiggins,12.787,16.6,0.0
406,1999,ohiggins,12.672,16.3,0.0
390,2000,ohiggins,12.533,15.9,0.0
374,2001,ohiggins,12.183,15.2,0.0
358,2002,ohiggins,11.978,14.8,0.0
342,2003,ohiggins,11.799,14.4,0.0
326,2004,ohiggins,13.382,14.9,0.0
310,2005,ohiggins,12.408,14.8,0.0
294,2006,ohiggins,11.517,13.6,0.0
278,2007,ohiggins,12.199,14.3,0.0
262,2008,ohiggins,12.592,14.7,0.0
246,2009,ohiggins,12.731,14.6,0.0
230,2010,ohiggins,12.723,14.4,0.0
214,2011,ohiggins,12.189,13.8,0.0
198,2012,ohiggins,12.119,13.6,0.0
182,2013,ohiggins,12.113,13.5,0.0
166,2014,ohiggins,12.412,13.7,0.0
150,2015,ohiggins,12.050,13.2,0.1
134,2016,ohiggins,11.416,12.4,1.5
118,2017,ohiggins,10.887,11.4,2.9
102,2018,ohiggins,11.248,11.6,9.4
86,2019,ohiggins,10.756,11.0,11.4
70,2020,ohiggins,10.245,10.4,11.3
54,2021,ohiggins,9.258,9.3,11.4
38,2022,ohiggins,10.072,10.0,14.4
496,1993,tarapaca,4.128,21.7,0.0
480,1994,tarapaca,7.575,21.1,0.0
464,1995,tarapaca,7.746,21.1,0.0
448,1996,tarapaca,8.058,21.6,0.0
432,1997,tarapaca,8.009,21.1,0.0
416,1998,tarapaca,8.157,21.1,0.0
400,1999,tarapaca,8.086,20.6,0.0
384,2000,tarapaca,8.070,20.2,0.0
368,2001,tarapaca,7.928,19.6,0.0
352,2002,tarapaca,7.571,18.4,0.0
336,2003,tarapaca,7.732,18.5,0.0
320,2004,tarapaca,4.821,17.7,0.0
304,2005,tarapaca,5.024,18.0,0.0
288,2006,tarapaca,4.761,16.7,0.0
272,2007,tarapaca,5.017,17.1,0.0
256,2008,tarapaca,5.287,17.8,0.0
240,2009,tarapaca,5.692,18.7,0.0
224,2010,tarapaca,5.637,18.0,0.0
208,2011,tarapaca,5.753,18.1,0.0
192,2012,tarapaca,5.721,18.4,0.0
176,2013,tarapaca,5.766,18.1,0.0
160,2014,tarapaca,5.835,17.8,0.0
144,2015,tarapaca,5.712,17.1,18.6
128,2016,tarapaca,5.419,15.9,27.5
112,2017,tarapaca,5.081,14.9,31.7
96,2018,tarapaca,4.955,14.0,33.7
80,2019,tarapaca,4.878,13.2,36.9
64,2020,tarapaca,4.709,12.3,39.2
48,2021,tarapaca,4.396,11.3,44.9
32,2022,tarapaca,5.023,12.7,47.9
510,1993,valparaiso,27.101,19.0,0.0
494,1994,valparaiso,27.089,18.7,0.0
478,1995,valparaiso,26.050,17.7,0.0
462,1996,valparaiso,25.781,17.3,0.0
446,1997,valparaiso,25.314,16.8,0.0
430,1998,valparaiso,25.097,16.5,0.0
414,1999,valparaiso,24.546,15.9,0.0
398,2000,valparaiso,24.325,15.6,0.0
382,2001,valparaiso,23.870,15.1,0.0
366,2002,valparaiso,23.172,14.5,0.0
350,2003,valparaiso,22.481,13.9,0.0
334,2004,valparaiso,23.118,14.1,0.0
318,2005,valparaiso,23.409,14.1,0.0
302,2006,valparaiso,21.672,13.0,0.0
286,2007,valparaiso,22.659,13.4,0.0
270,2008,valparaiso,23.116,13.5,0.0
254,2009,valparaiso,23.735,13.7,0.0
238,2010,valparaiso,23.788,13.5,0.0
222,2011,valparaiso,23.568,13.3,0.0
206,2012,valparaiso,23.619,13.3,0.0
190,2013,valparaiso,23.127,13.0,0.0
174,2014,valparaiso,24.125,13.4,0.0
158,2015,valparaiso,23.598,13.0,1.5
142,2016,valparaiso,22.165,12.1,2.2
126,2017,valparaiso,20.357,10.8,3.0
110,2018,valparaiso,21.002,11.0,9.7
94,2019,valparaiso,19.619,10.1,11.8
78,2020,valparaiso,18.427,9.4,10.8
62,2021,valparaiso,16.822,8.5,11.1
46,2022,valparaiso,17.903,9.0,12.6

In [ ]:
grafico_final = alt.Chart(df_lineas).mark_line(point=True).encode(
    x=alt.X(
        "ano:O",
        title="Año"
    ),
    y=alt.Y(
        "tasa_natalidad_1000:Q",
        title="Tasa de natalidad por cada 1.000 habitantes"
    ),
    color=alt.Color(
        "region:N",
        title="Región"
    ),
    tooltip=[
        alt.Tooltip("ano:O", title="Año"),
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("tasa_natalidad_100:Q", title="Tasa de Natalidad", format=".2f")
    ]
).properties(
    title="Evolución de la tasa de natalidad por región en Chile",
    width=800,
    height=500
).interactive()

grafico_final

alt.Chart(...)

In [ ]:
import pandas as pd

# Ensure 'df' is loaded, as 'df_limpia' depends on it.
df = pd.read_csv("/content/Base de datos infante.csv", sep=';')

# Define df_limpia filtering for years <= 2022
df_limpia = df[df["ano"] <= 2022].copy()

# Convert 'tasa_natalidad_1000' to numeric, handling commas as decimal separators
if df_limpia['tasa_natalidad_1000'].dtype == 'object':
    df_limpia.loc[:, "tasa_natalidad_1000"] = df_limpia["tasa_natalidad_1000"].str.replace(',', '.', regex=False).astype(float)

# Convert 'porcentajes_madres_extranjeras' to numeric, handling commas and '0000000000000000'
if df_limpia['porcentajes_madres_extranjeras'].dtype == 'object':
    df_limpia.loc[:, "porcentajes_madres_extranjeras"] = (
        df_limpia["porcentajes_madres_extranjeras"]
        .astype(str)
        .str.replace(',', '.', regex=False)
        .replace('0000000000000000', '0')
        .astype(float)
    )

# Display the head to confirm data types and content (optional, can be removed after verification)
# display(df_limpia.head())

In [ ]:
import pandas as pd
import altair as alt
df_ranking = df_limpia.copy()
#convertir año a número
df_ranking["ano"] = pd.to_numeric(df_ranking["ano"], errors="coerce")
#convertir tasa de natalidad a número
df_ranking["tasa_natalidad_1000"] = df_ranking["tasa_natalidad_1000"].astype(str).str.replace(",", ".", regex=False)
df_ranking["tasa_natalidad_1000"] = pd.to_numeric(df_ranking["tasa_natalidad_1000"], errors="coerce")
#dejar solo datos completos
regiones_antiguas = [
    "tarapaca",
    "antofagasta",
    "atacama",
    "coquimbo",
    "valparaiso",
    "metropolitana",
    "ohiggins",
    "maule",
    "biobio",
    "la_araucania",
    "los_lagos",
    "aysen",
    "magallanes"
]

df_1993_2022 = df_ranking[
    (df_ranking["ano"].isin([1993, 2022])) &
    (df_ranking["region"].isin(regiones_antiguas))
]

df_inicio_1993 = df_1993_2022[df_1993_2022["ano"] == 1993][["region", "tasa_natalidad_1000"]].rename(
    columns={"tasa_natalidad_1000": "tasa_inicio"}
)

df_final_2022 = df_1993_2022[df_1993_2022["ano"] == 2022][["region", "tasa_natalidad_1000"]].rename(
    columns={"tasa_natalidad_1000": "tasa_final"}
)

cambio_tasa_1993_2022 = df_inicio_1993.merge(df_final_2022, on="region")

cambio_tasa_1993_2022["cambios_tasa"] = cambio_tasa_1993_2022["tasa_final"] - cambio_tasa_1993_2022["tasa_inicio"]

grafico_barras_tasa_1993_2022 = alt.Chart(cambio_tasa_1993_2022).mark_bar().encode(
    x=alt.X(
        "cambios_tasa:Q",
        title="Cambio en la tasa de natalidad"
    ),
    y=alt.Y(
        "region:N",
        sort="x",
        title="Región"
    ),
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("tasa_inicio:Q", title="Tasa 1993", format=".2f"),
        alt.Tooltip("tasa_final:Q", title="Tasa 2022", format=".2f"),
        alt.Tooltip("cambios_tasa:Q", title="Cambio total", format=".2f")
    ]
).properties(
    title="Regiones donde más cambió la tasa de natalidad, 1993-2022",
    width=750,
    height=500
)

grafico_barras_tasa_1993_2022

alt.Chart(...)

In [ ]:
grafico_barras_tasa_1993_2022.save("grafico_barras_tasa_1993_2022.html")

In [ ]:
grafico_barras_tasa_1993_2022.save("grafico_barras_tasa_1993_2022.png")

In [ ]:
from PIL import Image
img = Image.open("grafico_barras_tasa_1993_2022.png").convert("RGB")
img.save("grafico_barras_tasa_1993_2022.jpg")

In [ ]:
from google.colab import files
files.download("grafico_barras_tasa_1993_2022.html")
files.download("grafico_barras_tasa_1993_2022.jpg")

In [ ]:
df_2012_2022 = df_ranking[
    df_ranking["ano"].isin([2012, 2022])
]

df_inicio_2012 = df_2012_2022[df_2012_2022["ano"] == 2012][["region", "tasa_natalidad_1000"]].rename(
    columns={"tasa_natalidad_1000": "tasa_inicio"}
)

df_final_2022 = df_2012_2022[df_2012_2022["ano"] == 2022][["region", "tasa_natalidad_1000"]].rename(
    columns={"tasa_natalidad_1000": "tasa_final"}
)

cambio_tasa_2012_2022 = df_inicio_2012.merge(df_final_2022, on="region")

cambio_tasa_2012_2022["cambios_tasa"] = cambio_tasa_2012_2022["tasa_final"] - cambio_tasa_2012_2022["tasa_inicio"]

grafico_barras_tasa_2012_2022 = alt.Chart(cambio_tasa_2012_2022).mark_bar().encode(
    x=alt.X(
        "cambios_tasa:Q",
        title="Cambio en la tasa de natalidad"
    ),
    y=alt.Y(
        "region:N",
        sort="x",
        title="Región"
    ),
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("tasa_inicio:Q", title="Tasa 2012", format=".2f"),
        alt.Tooltip("tasa_final:Q", title="Tasa 2022", format=".2f"),
        alt.Tooltip("cambios_tasa:Q", title="Cambio total", format=".2f")
    ]
).properties(
    title="Regiones donde más cambió la tasa de natalidad, 2012-2022",
    width=750,
    height=500
)

grafico_barras_tasa_2012_2022

alt.Chart(...)

In [ ]:
grafico_barras_tasa_2012_2022.save("grafico_barras_tasa_2012_2022.html")
grafico_barras_tasa_2012_2022.save("grafico_barras_tasa_2012_2022.html")

In [ ]:
grafico_barras_tasa_2012_2022

alt.Chart(...)

In [ ]:
grafico_barras_tasa_2012_2022.save("grafico_barras_tasa_2012_2022.html")

In [ ]:
from google.colab import files
from PIL import Image

grafico_barras_tasa_2012_2022.save("grafico_barras_tasa_2012_2022.html")

grafico_barras_tasa_2012_2022.save("grafico_barras_tasa_2012_2022.png")
img = Image.open("grafico_barras_tasa_2012_2022.png").convert("RGB")
img.save("grafico_barras_tasa_2012_2022.jpg")

files.download("grafico_barras_tasa_2012_2022.html")
files.download("grafico_barras_tasa_2012_2022.jpg")

In [ ]:
from google.colab import files

grafico_barras_tasa_1993_2022.save("grafico_barras_tasa_1993_2022.html")

files.download("grafico_barras_tasa_1993_2022.png")

In [ ]:
from google.colab import files

grafico_barras_tasa_1993_2022.save("grafico_barras_tasa_1993_2022.html")

files.download("grafico_barras_tasa_1993_2022.html")

In [ ]:
import pandas as pd
import altair as alt

df_ranking = df_limpia.copy()

df_ranking["ano"] = pd.to_numeric(df_ranking["ano"], errors="coerce")

df_ranking["tasa_natalidad_1000"] = (
    df_ranking["tasa_natalidad_1000"]
    .astype(str)
    .str.replace(",", ".", regex=False)
)

df_ranking["tasa_natalidad_1000"] = pd.to_numeric(
    df_ranking["tasa_natalidad_1000"],
    errors="coerce"
)

df_ranking = df_ranking.dropna(subset=["ano", "region", "tasa_natalidad_1000"])

In [ ]:
orden_norte_sur_todas = [
    "arica_parinacota",
    "tarapaca",
    "antofagasta",
    "atacama",
    "coquimbo",
    "valparaiso",
    "metropolitana",
    "ohiggins",
    "maule",
    "nuble",
    "biobio",
    "la_araucania",
    "los_rios",
    "los_lagos",
    "aysen",
    "magallanes"
]

orden_norte_sur_antiguas = [
    "tarapaca",
    "antofagasta",
    "atacama",
    "coquimbo",
    "valparaiso",
    "metropolitana",
    "ohiggins",
    "maule",
    "biobio",
    "la_araucania",
    "los_lagos",
    "aysen",
    "magallanes"
]

In [ ]:
df_1993 = df_ranking[
    (df_ranking["ano"] == 1993) &
    (df_ranking["region"].isin(orden_norte_sur_antiguas))
][["region", "tasa_natalidad_1000"]].rename(
    columns={"tasa_natalidad_1000": "tasa_1993"}
)

df_2022 = df_ranking[
    (df_ranking["ano"] == 2022) &
    (df_ranking["region"].isin(orden_norte_sur_antiguas))
][["region", "tasa_natalidad_1000"]].rename(
    columns={"tasa_natalidad_1000": "tasa_2022"}
)

rango_1993_2022 = df_1993.merge(df_2022, on="region")

rango_1993_2022["inicio_barra"] = rango_1993_2022[["tasa_1993", "tasa_2022"]].min(axis=1)
rango_1993_2022["fin_barra"] = rango_1993_2022[["tasa_1993", "tasa_2022"]].max(axis=1)
rango_1993_2022["cambio"] = rango_1993_2022["tasa_2022"] - rango_1993_2022["tasa_1993"]

grafico_rango_1993_2022 = alt.Chart(rango_1993_2022).mark_bar(size=18).encode(
    x=alt.X(
        "inicio_barra:Q",
        title="Tasa de natalidad por cada 1.000 habitantes"
    ),
    x2="fin_barra:Q",
    y=alt.Y(
        "region:N",
        sort=orden_norte_sur_antiguas,
        title="Región"
    ),
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("tasa_1993:Q", title="Tasa 1993", format=".2f"),
        alt.Tooltip("tasa_2022:Q", title="Tasa 2022", format=".2f"),
        alt.Tooltip("cambio:Q", title="Cambio", format=".2f")
    ]
).properties(
    title="Cambio en la tasa de natalidad por región, 1993-2022",
    width=750,
    height=500
)

grafico_rango_1993_2022

alt.Chart(...)

In [ ]:
df_2012 = df_ranking[
    (df_ranking["ano"] == 2012) &
    (df_ranking["region"].isin(orden_norte_sur_todas))
][["region", "tasa_natalidad_1000"]].rename(
    columns={"tasa_natalidad_1000": "tasa_2012"}
)

df_2022 = df_ranking[
    (df_ranking["ano"] == 2022) &
    (df_ranking["region"].isin(orden_norte_sur_todas))
][["region", "tasa_natalidad_1000"]].rename(
    columns={"tasa_natalidad_1000": "tasa_2022"}
)

rango_2012_2022 = df_2012.merge(df_2022, on="region")

rango_2012_2022["inicio_barra"] = rango_2012_2022[["tasa_2012", "tasa_2022"]].min(axis=1)
rango_2012_2022["fin_barra"] = rango_2012_2022[["tasa_2012", "tasa_2022"]].max(axis=1)
rango_2012_2022["cambio"] = rango_2012_2022["tasa_2022"] - rango_2012_2022["tasa_2012"]

grafico_rango_2012_2022 = alt.Chart(rango_2012_2022).mark_bar(size=18).encode(
    x=alt.X(
        "inicio_barra:Q",
        title="Tasa de natalidad por cada 1.000 habitantes"
    ),
    x2="fin_barra:Q",
    y=alt.Y(
        "region:N",
        sort=orden_norte_sur_todas,
        title="Región"
    ),
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("tasa_2012:Q", title="Tasa 2012", format=".2f"),
        alt.Tooltip("tasa_2022:Q", title="Tasa 2022", format=".2f"),
        alt.Tooltip("cambio:Q", title="Cambio", format=".2f")
    ]
).properties(
    title="Cambio en la tasa de natalidad por región, 2012-2022",
    width=750,
    height=550
)

grafico_rango_2012_2022

alt.Chart(...)

In [ ]:
grafico_rango_1993_2022.save("grafico_rango_tasa_1993_2022.html")
grafico_rango_2012_2022.save("grafico_rango_tasa_2012_2022.html")

In [ ]:
from google.colab import files

files.download("grafico_rango_tasa_1993_2022.html")
files.download("grafico_rango_tasa_2012_2022.html")

In [ ]:
from PIL import Image

# Save the 1993-2022 chart as PNG and then convert to JPG
grafico_rango_1993_2022.save("grafico_rango_tasa_1993_2022.png", scale_factor=3)
img_1993 = Image.open("grafico_rango_tasa_1993_2022.png").convert("RGB")
img_1993.save("grafico_rango_tasa_1993_2022.jpg")

# Save the 2012-2022 chart as PNG and then convert to JPG
grafico_rango_2012_2022.save("grafico_rango_tasa_2012_2022.png", scale_factor=3)
img_2012 = Image.open("grafico_rango_tasa_2012_2022.png").convert("RGB")
img_2012.save("grafico_rango_tasa_2012_2022.jpg")

from google.colab import files
files.download("grafico_rango_tasa_1993_2022.jpg")
files.download("grafico_rango_tasa_2012_2022.jpg")

In [ ]:
#grafico: proporción de nacimientos según origen de la madre por región
import pandas as pd
import altair as alt
df_proporcion = df_limpia.copy()
#convertir año a número
df_proporcion["ano"] = pd.to_numeric(df_proporcion["ano"], errors="coerce")
#convertir porcentaje de madres extranjeras a número
df_proporcion["porcentajes_madres_extranjeras"] = df_proporcion["porcentajes_madres_extranjeras"].astype(str).str.replace(",", ".", regex=False)
df_proporcion["porcentajes_madres_extranjeras"] = pd.to_numeric(df_proporcion["porcentajes_madres_extranjeras"], errors="coerce")
#dejar solo filas con datos completos
df_proporcion = df_proporcion.dropna(subset=["ano", "region", "porcentajes_madres_extranjeras"])
#crear porcentaje complementario
df_proporcion["porcentaje_madres_internas"] = 100 - df_proporcion["porcentajes_madres_extranjeras"]
#crear tabla con año inicial
df_inicio = df_proporcion[df_proporcion["ano"] == df_proporcion["ano"].min()]
#transformar a formato largo
df_proporcion_largo = df_proporcion.melt(id_vars=["ano", "region"], value_vars=["porcentajes_madres_extranjeras", "porcentaje_madres_internas"], var_name="origen_madre", value_name="porcentaje")
#renombrar categorías para que se entienda mejor
df_proporcion_largo["origen_madre"] = df_proporcion_largo["origen_madre"].replace({
    "porcentaje_madres_internas": "madres chilenas",
    "porcentajes_madres_extranjeras": "madres extranjeras"})
# Orden de regiones de norte a sur
orden_norte_sur = [
    "arica_parinacota",
    "tarapaca",
    "antofagasta",
    "atacama",
    "coquimbo",
    "valparaiso",
    "metropolitana",
    "ohiggins",
    "maule",
    "nuble",
    "biobio",
    "la_araucania",
    "los_rios",
    "los_lagos",
    "aysen",
    "magallanes"
]

# Selector de año
selector_ano = alt.binding_select(
    options=sorted(df_proporcion_largo["ano"].unique().tolist()),
    name="Año: "
)

param_ano = alt.param(
    name="Seleccionar_anio",
    bind=selector_ano,
    value=int(df_proporcion_largo["ano"].max())
)

# Crear gráfico
grafico_proporcion = alt.Chart(df_proporcion_largo).mark_bar().encode(
    y=alt.Y(
        "region:N",
        sort=orden_norte_sur,
        title="Región"
    ),
    x=alt.X(
        "porcentaje:Q",
        stack="normalize",
        title="Distribución de nacimientos según origen de la madre"
    ),
    color=alt.Color(
        "origen_madre:N",
        title="Origen de la madre"
    ),
    tooltip=[
        alt.Tooltip("ano:O", title="Año"),
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("origen_madre:N", title="Origen de la madre"),
        alt.Tooltip("porcentaje:Q", title="Porcentaje", format=".2f")
    ]
).add_params(
    param_ano
).transform_filter(
    alt.datum.ano == param_ano
).properties(
    title="Proporción de nacimientos según origen de la madre por región",
    width=850,
    height=520
).interactive()

grafico_proporcion

alt.Chart(...)

In [ ]:
grafico_proporcion.save("grafico_proporcion.html")

In [ ]:
grafico_proporcion.save("grafico_proporcion.png")

In [ ]:
from PIL import Image
img = Image.open("grafico_proporcion.png").convert("RGB")
img.save("grafico_proporcion.jpg")

In [ ]:
from google.colab import files
files.download("grafico_proporcion.html")
files.download("grafico_proporcion.jpg")

In [ ]:
grafico_final.save("grafico_lineas.html")

In [ ]:
grafico_final.save("grafico_lineas.png")

In [ ]:
from PIL import Image
img = Image.open("grafico_lineas.png").convert("RGB")
img.save("grafico_lineas.jpg")

In [ ]:
from google.colab import files
files.download("grafico_lineas.html")
files.download("grafico_lineas.jpg")

In [ ]:
grafico_barras.save("grafico_barras.html")

In [ ]:
grafico_barras.save("grafico_barras.png")

In [ ]:
from PIL import Image
img = Image.open("grafico_barras.png").convert("RGB")
img.save("grafico_barras.jpg")

In [ ]:
from google.colab import files
files.download("grafico_barras.html")
files.download("grafico_barras.jpg")

In [ ]:
grafico_barras_top5.save("grafico_barras_top5.html")

In [ ]:
grafico_barras_top5.save("grafico_barras_top5.png")

In [ ]:
from PIL import Image
img = Image.open("grafico_barras_top5.png").convert("RGB")
img.save("grafico_barras_top5.jpg")

In [ ]:
from google.colab import files
files.download("grafico_barras_top5.html")
files.download("grafico_barras_top5.jpg")